In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import yfinance as yf
import datetime
import xgboost

from scipy.stats import norm
from scipy.integrate import quad
from scipy.optimize import minimize, least_squares, newton, differential_evolution, dual_annealing
from scipy.special import ndtr

from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score, mean_absolute_percentage_error, mean_squared_error, mean_squared_log_error
from sklearn.inspection import permutation_importance
from xgboost import XGBRegressor
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.metrics import r2_score
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
from scipy.interpolate import griddata
from scipy.optimize import brentq

from sklearn.preprocessing import StandardScaler
from joblib import Parallel, delayed
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from itertools import repeat
import random
import os as _os
import json as _json

In [2]:
### Adapted ML code to output whole dataset (train + test data) instead of only test data

path = "C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\data_output_final\data_output_2003_top3_qual.dta"
data = pd.read_stata(path)
data = data.drop(["index"], axis = 1)

In [2]:
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

In [ ]:
# Load Optuna optimised hyperparameters
_bp_path = 'C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\optuna_best_params.json'
_best    = _json.load(open(_bp_path)) if _os.path.exists(_bp_path) else {}

params_xgb_ivol             = _best.get('xgb_ivol',             {})
params_ann_ivol             = _best.get('ann_ivol',              {})
params_lbfgs_ivol           = _best.get('lbfgs_ivol',           {})
params_xgb_price            = _best.get('xgb_price',            {})
params_ann_price            = _best.get('ann_price',             {})
params_lbfgs_price          = _best.get('lbfgs_price',          {})
params_xgb_surface_ivol     = _best.get('xgb_surface_ivol',     {})
params_ann_surface_ivol     = _best.get('ann_surface_ivol',      {})
params_lbfgs_surface_ivol   = _best.get('lbfgs_surface_ivol',   {})
params_xgb_surface_price    = _best.get('xgb_surface_price',    {})
params_ann_surface_price    = _best.get('ann_surface_price',     {})
params_lbfgs_surface_price  = _best.get('lbfgs_surface_price',  {})
params_ann_variable_ivol    = _best.get('ann_variable_ivol',     {})
params_lbfgs_variable_ivol  = _best.get('lbfgs_variable_ivol',  {})
params_ann_variable_price   = _best.get('ann_variable_price',    {})
params_lbfgs_variable_price = _best.get('lbfgs_variable_price', {})

if _best:
    print("Loaded Optuna params for:", list(_best.keys()))
else:
    print("optuna_best_params.json not found — using hardcoded defaults")

Loaded Optuna params for: ['xgb_ivol', 'ann_ivol', 'lbfgs_ivol', 'xgb_price', 'ann_price', 'lbfgs_price', 'xgb_surface_ivol', 'ann_surface_ivol', 'lbfgs_surface_ivol', 'xgb_surface_price', 'ann_surface_price', 'lbfgs_surface_price', 'ann_variable_ivol', 'lbfgs_variable_ivol', 'ann_variable_price', 'lbfgs_variable_price']

Implied Volatility Models

In [6]:
##### AGBoost ML calibration and estimation functions:

def XGB_function(data, x_cols, y_cols, params=None, compute_importance=False):
    
    X, Y = data[x_cols].copy(), data[y_cols].copy()

    dates  = data["date"].sort_values().unique()
    cutoff = dates[int(len(dates) * 0.7)]
    train_mask = data["date"] < cutoff
    X_train, X_test = X[train_mask].copy(), X[~train_mask].copy()
    Y_train, Y_test = Y[train_mask].copy(), Y[~train_mask].copy()

    train_dates = data.loc[train_mask, "date"].sort_values().unique()
    val_cutoff  = train_dates[int(len(train_dates) * 0.9)]
    val_mask    = train_mask & (data["date"] >= val_cutoff)
    X_val,   Y_val   = X[val_mask].copy(),              Y[val_mask].copy()
    X_train, Y_train = X[train_mask & ~val_mask].copy(), Y[train_mask & ~val_mask].copy()

    X_train_encoded_ivol = X_train
    X_val_encoded_ivol = X_val
    X_test_encoded_ivol = X_test
    Y_train_ivol = Y_train
    Y_val_ivol = Y_val
    Y_test_ivol = Y_test


    _p = params or {}
    model_xgb_ivol = xgboost.XGBRegressor(
        gamma         = _p.get('gamma',         1),
        learning_rate = _p.get('learning_rate', 0.1),
        max_depth     = _p.get('max_depth',     20),
        n_estimators  = _p.get('n_estimators',  200),
        subsample     = _p.get('subsample',     1),
        reg_lambda    = _p.get('reg_lambda',    1),
        eval_metric='rmse', tree_method='hist', device='cuda',
    )

    model_xgb_ivol.fit(X_train_encoded_ivol, Y_train_ivol, verbose=False,
                       eval_set=[(X_val_encoded_ivol, Y_val_ivol)])

    y_pred_xgb_ivol       = model_xgb_ivol.predict(X_test_encoded_ivol)
    y_pred_xgb_ivol_val   = model_xgb_ivol.predict(X_val_encoded_ivol)
    y_pred_xgb_ivol_train = model_xgb_ivol.predict(X_train_encoded_ivol)

    rmse_xgb_ivol = np.sqrt(mean_squared_error(Y_test_ivol, y_pred_xgb_ivol))
    mse_xgb_ivol = mean_squared_error(Y_test_ivol, y_pred_xgb_ivol)
    mape_xgb_ivol = mean_absolute_percentage_error(Y_test_ivol, y_pred_xgb_ivol)
    rsquared_xgb_ivol = r2_score(Y_test_ivol, y_pred_xgb_ivol)


    print("mse:", mse_xgb_ivol)
    print("rmse:", rmse_xgb_ivol)
    print("mape:", mape_xgb_ivol)
    print("rsquared:", rsquared_xgb_ivol)

    importance_df = None
    if compute_importance:
        xgb_gain = model_xgb_ivol.feature_importances_
        perm_xgb = permutation_importance(
            model_xgb_ivol, X_test_encoded_ivol.values.astype(np.float32),
            Y_test_ivol.values.ravel().astype(np.float32),
            n_repeats=10, scoring='neg_mean_squared_error', random_state=42
        )
        importance_df = pd.DataFrame({
            'feature': x_cols,
            'xgb_gain_importance': xgb_gain,
            'xgb_perm_mean': perm_xgb.importances_mean,
            'xgb_perm_std': perm_xgb.importances_std,
        }).set_index('feature').sort_values('xgb_perm_mean', ascending=False)
        print("  Feature importance computed")


    output_xgb_ivol = pd.concat([X_test_encoded_ivol, 
                                 Y_test_ivol.set_axis(X_test_encoded_ivol.index), 
                                 pd.DataFrame(y_pred_xgb_ivol, columns = ["output_xgb"]).set_axis(X_test_encoded_ivol.index)], axis=1)
    output_xgb_ivol_val = pd.concat([X_val_encoded_ivol,
                                     Y_val_ivol.set_axis(X_val_encoded_ivol.index),
                                     pd.DataFrame(y_pred_xgb_ivol_val, columns=["output_xgb"]).set_axis(X_val_encoded_ivol.index)], axis=1)
    output_xgb_ivol_train = pd.concat([X_train_encoded_ivol, 
                                      Y_train_ivol.set_axis(X_train_encoded_ivol.index), 
                                      pd.DataFrame(y_pred_xgb_ivol_train, columns = ["output_xgb"]).set_axis(X_train_encoded_ivol.index)], axis=1)

    output_xgb_ivol["out_of_sample"] = 1
    output_xgb_ivol_val["out_of_sample"] = 0
    output_xgb_ivol_train["out_of_sample"] = 0

    output_xgb_ivol_full = pd.concat([output_xgb_ivol_train, output_xgb_ivol_val, output_xgb_ivol], axis = 0)

    data_clean = data.drop(columns = [col for col in data.columns if col in output_xgb_ivol_full.columns])
    data_out = pd.concat([data_clean, output_xgb_ivol_full], axis = 1)

    data_out["mse_optim"] = mse_xgb_ivol
    data_out["rmse_optim"] = rmse_xgb_ivol
    data_out["mape_optim"] = mape_xgb_ivol
    data_out["rsquared_optim"] = rsquared_xgb_ivol

    if compute_importance:
        return data_out, importance_df
    return data_out

In [9]:
# ML data prep, modelling option implied volatility
set_seed(42)
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['impl_volatility']


output_xgb_ivol, importance_xgb_ivol = XGB_function(data, selected_columns_x, selected_columns_y, params=params_xgb_ivol, compute_importance=True)
output_xgb_ivol = output_xgb_ivol.rename(columns={"output_xgb":"impl_vol_xgb"})
output_xgb_ivol

c:\Users\chril\torch_gpu\Lib\site-packages\xgboost\core.py:751: UserWarning: [23:02:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

mse: 0.005232819821685553
rmse: 0.0723382320884714
mape: 0.17130212485790253
rsquared: 0.7205931544303894
  Feature importance computed

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,ddelta,dgamma,...,stock_price,realized_vol,moneyness,impl_volatility,impl_vol_xgb,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2002-01-02,2002-01-19,C,105.0,0.2,0.30,34.0,59.0,0.134418,0.057799,...,100.73,0.004923,0.041517,0.183356,0.151205,0,0.005233,0.072338,0.171302,0.720593
1,2002-01-02,2002-01-19,C,106.0,0.1,0.15,6.0,260.0,0.078105,0.040581,...,100.73,0.004923,0.050995,0.176133,0.151205,0,0.005233,0.072338,0.171302,0.720593
2,2002-01-02,2002-01-19,C,90.0,10.5,11.00,0.0,160.0,0.974934,0.009727,...,100.73,0.004923,-0.112634,0.284675,0.292717,0,0.005233,0.072338,0.171302,0.720593
3,2002-01-02,2002-01-19,C,91.0,9.6,10.00,0.0,30.0,0.957577,0.014793,...,100.73,0.004923,-0.101584,0.293254,0.292717,0,0.005233,0.072338,0.171302,0.720593
4,2002-01-02,2002-01-19,C,92.0,8.6,9.00,0.0,612.0,0.954278,0.017296,...,100.73,0.004923,-0.090655,0.266864,0.265531,0,0.005233,0.072338,0.171302,0.720593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166267,2002-12-31,2003-09-20,P,925.0,101.3,101.50,0.0,996.0,-0.553557,0.002103,...,879.82,0.234007,0.050076,0.248388,0.309065,1,0.005233,0.072338,0.171302,0.720593
166268,2002-12-31,2003-09-20,P,950.0,116.0,116.20,0.0,639.0,-0.607127,0.002091,...,879.82,0.234007,0.076745,0.242036,0.309065,1,0.005233,0.072338,0.171302,0.720593
166269,2002-12-31,2003-09-20,P,975.0,132.2,132.40,0.0,1256.0,-0.659065,0.002032,...,879.82,0.234007,0.102720,0.236583,0.309065,1,0.005233,0.072338,0.171302,0.720593
166270,2002-12-31,2003-09-20,P,900.0,88.1,88.30,1.0,1941.0,-0.499880,0.002068,...,879.82,0.234007,0.022677,0.255549,0.309065,1,0.005233,0.072338,0.171302,0.720593
166271,2002-12-31,2003-09-20,C,1300.0,0.6,0.80,0.0,426.0,0.013810,0.000231,...,879.82,0.234007,0.390402,0.204509,0.402595,1,0.005233,0.072338,0.171302,0.720593

In [6]:
##### ANN torch calibration and estimation function with code data pipeline correction:
def ANN_function_torch_LBFGS(data, x_cols, y_cols, ignore, batch = 230000, log_y = False, params=None, compute_importance=False):

    X, Y = data[x_cols].copy(), data[y_cols].copy()
    
    dates  = data["date"].sort_values().unique()
    cutoff = dates[int(len(dates) * 0.7)]
    train_mask = data["date"] < cutoff
    X_train, X_test = X[train_mask].copy(), X[~train_mask].copy()
    Y_train, Y_test = Y[train_mask].copy(), Y[~train_mask].copy()

    train_dates = data.loc[train_mask, "date"].sort_values().unique()
    val_cutoff  = train_dates[int(len(train_dates) * 0.9)]
    val_mask    = train_mask & (data["date"] >= val_cutoff)
    X_val,   Y_val   = X[val_mask].copy(),              Y[val_mask].copy()
    X_train, Y_train = X[train_mask & ~val_mask].copy(), Y[train_mask & ~val_mask].copy()


    scaler_X_ivol = StandardScaler()

    non_categ_cols_ivol = [col for col in X_train.columns if col not in ignore]
    X_train_encoded_ivol_std = X_train
    X_test_encoded_ivol_std = X_test
    X_val_encoded_ivol_std = X_val
    X_train_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.fit_transform(X_train_encoded_ivol_std[non_categ_cols_ivol])
    X_test_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.transform(X_test_encoded_ivol_std[non_categ_cols_ivol])
    X_val_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.transform(X_val_encoded_ivol_std[non_categ_cols_ivol])

    if log_y:
        Y_train_ivol_std = np.log(Y_train)
        Y_test_ivol_std  = np.log(Y_test)
        Y_val_ivol_std   = np.log(Y_val)
    else:
        Y_train_ivol_std = Y_train
        Y_test_ivol_std  = Y_test
        Y_val_ivol_std   = Y_val


    _p           = params or {}
    n_layers     = _p.get('n_layers',     3)
    n_units      = _p.get('n_units',      64)
    max_iter     = _p.get('max_iter',     100)
    history_size = _p.get('history_size', 10)


    class MLP(nn.Module):
        def __init__(self, n_features):
            super().__init__()
            layers = [nn.Linear(n_features, n_units), nn.GELU()]
            for _ in range(n_layers - 1):
                layers += [nn.Linear(n_units, n_units), nn.GELU()]
            layers.append(nn.Linear(n_units, 1))
            self.net = nn.Sequential(*layers)

        def forward(self, x):
            return self.net(x) if log_y else torch.nn.functional.softplus(self.net(x))

    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")


    model = MLP(len(X_train_encoded_ivol_std.columns)).to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.LBFGS(
        model.parameters(),
        max_iter=max_iter,
        history_size=history_size,
        line_search_fn="strong_wolfe",
        tolerance_grad=1e-7,
        tolerance_change=1e-9,
    )


    def closure():
            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()
            return loss




    n = len(X_train_encoded_ivol_std)

    X_val_t = torch.as_tensor(X_val_encoded_ivol_std.values, device=device, dtype=torch.float32)
    Y_val_t = torch.as_tensor(Y_val_ivol_std.values, device=device, dtype=torch.float32)

    best_val_loss = float("inf")
    patience = 15
    counter = 0
    for epoch in range(50):
        for i in range(0, n, batch):
            model.train()
            end = min(i + batch, n)
            total_loss = 0
            xb = torch.as_tensor(X_train_encoded_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)
            yb = torch.as_tensor(Y_train_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)
            
            loss_temp = optimizer.step(closure)
            total_loss += loss_temp.detach().item()

        model.eval()
        with torch.no_grad():
            val_loss = criterion(model(X_val_t), Y_val_t)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_model = model.state_dict()
            counter = 0
        else:
            counter += 1

        if counter >= patience:
            break
        print(f"Run {epoch:03d} | Training Loss: {total_loss:.4f}")
        print(f"Run {epoch:03d} | Best Validation Loss: {best_val_loss:.4f}")

    model.load_state_dict(best_model)

    model.eval()
    with torch.no_grad():
        
        X_test_encoded_ivol_std_t = torch.from_numpy(X_test_encoded_ivol_std.values.astype(np.float32)).to(device)
        X_val_encoded_ivol_std_t = torch.from_numpy(X_val_encoded_ivol_std.values.astype(np.float32)).to(device)
        X_train_encoded_ivol_std_t = torch.from_numpy(X_train_encoded_ivol_std.values.astype(np.float32)).to(device)
        y_pred_ann_ivol = model(X_test_encoded_ivol_std_t).cpu().numpy()
        y_pred_ann_ivol_val = model(X_val_encoded_ivol_std_t).cpu().numpy()
        y_pred_ann_ivol_train = model(X_train_encoded_ivol_std_t).cpu().numpy()

    if log_y:
        y_pred_ann_ivol       = np.exp(y_pred_ann_ivol)
        y_pred_ann_ivol_val   = np.exp(y_pred_ann_ivol_val)
        y_pred_ann_ivol_train = np.exp(y_pred_ann_ivol_train)

    rmse_ann_ivol = np.sqrt(mean_squared_error(Y_test.values.ravel(), y_pred_ann_ivol))
    mse_ann_ivol = mean_squared_error(Y_test.values.ravel(), y_pred_ann_ivol)
    mape_ann_ivol = mean_absolute_percentage_error(Y_test.values.ravel(), y_pred_ann_ivol)
    rsquared_ann_ivol = r2_score(Y_test.values.ravel(), y_pred_ann_ivol)


    print("mse:", mse_ann_ivol)
    print("rmse:", rmse_ann_ivol)
    print("mape:", mape_ann_ivol)
    print("rsquared:", rsquared_ann_ivol)

    importance_df = None
    if compute_importance:
        class _TorchPredictor:
            def __init__(self, _model, _device):
                self._model = _model
                self._device = _device
            def predict(self, X):
                with torch.no_grad():
                    X_t = torch.tensor(X.astype(np.float32), device=self._device)
                    return self._model(X_t).cpu().numpy().ravel()

        predictor = _TorchPredictor(model, device)
        perm_ann = permutation_importance(
            predictor, X_test_encoded_ivol_std.values.astype(np.float32),
            Y_test_ivol_std.values.ravel().astype(np.float32),
            n_repeats=10, scoring='neg_mean_squared_error', random_state=42
        )
        importance_df = pd.DataFrame({
            'feature': x_cols,
            'ann_lbfgs_perm_mean': perm_ann.importances_mean,
            'ann_lbfgs_perm_std': perm_ann.importances_std,
        }).set_index('feature').sort_values('ann_lbfgs_perm_mean', ascending=False)
        print("  Feature importance computed")

    X_test_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_test_encoded_ivol_std[non_categ_cols_ivol])
    X_val_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_val_encoded_ivol_std[non_categ_cols_ivol])
    X_train_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_train_encoded_ivol_std[non_categ_cols_ivol])

    if log_y:
        Y_test_ivol_std  = np.exp(Y_test_ivol_std)
        Y_val_ivol_std   = np.exp(Y_val_ivol_std)
        Y_train_ivol_std = np.exp(Y_train_ivol_std)

    output_ann_ivol = pd.concat([X_test_encoded_ivol_std, 
                                 Y_test_ivol_std.set_axis(X_test_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol, columns = ["output_ann"]).set_axis(X_test_encoded_ivol_std.index)], axis=1)
    output_ann_ivol_val = pd.concat([X_val_encoded_ivol_std, 
                                 Y_val_ivol_std.set_axis(X_val_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol_val, columns = ["output_ann"]).set_axis(X_val_encoded_ivol_std.index)], axis=1)
    output_ann_ivol_train = pd.concat([X_train_encoded_ivol_std, 
                                 Y_train_ivol_std.set_axis(X_train_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol_train, columns = ["output_ann"]).set_axis(X_train_encoded_ivol_std.index)], axis=1)


    output_ann_ivol["out_of_sample"] = 1
    output_ann_ivol_val["out_of_sample"] = 0
    output_ann_ivol_train["out_of_sample"] = 0

    output_ann_ivol_full = pd.concat([output_ann_ivol_train, output_ann_ivol_val, output_ann_ivol], axis = 0)

    data_clean = data.drop(columns = [col for col in data.columns if col in output_ann_ivol_full.columns])
    data_out = pd.concat([data_clean, output_ann_ivol_full], axis = 1)

    data_out["mse_optim"] = mse_ann_ivol
    data_out["rmse_optim"] = rmse_ann_ivol
    data_out["mape_optim"] = mape_ann_ivol
    data_out["rsquared_optim"] = rsquared_ann_ivol

    if compute_importance:
        return data_out, importance_df
    return data_out

In [10]:
# ML data prep, modelling option implied volatility
set_seed(42)
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['impl_volatility']

ignore = ["cp_flag_one"]
output_ann_ivol_lbfgs = ANN_function_torch_LBFGS(data, selected_columns_x, selected_columns_y, ignore, params=params_lbfgs_ivol, compute_importance=False)
output_ann_ivol_lbfgs = output_ann_ivol_lbfgs.rename(columns={"output_ann":"impl_vol_ann"})
output_ann_ivol_lbfgs

Run 000 | Training Loss: 0.1918
Run 000 | Best Validation Loss: 0.0036
Run 001 | Training Loss: 0.0017
Run 001 | Best Validation Loss: 0.0030
Run 002 | Training Loss: 0.0013
Run 002 | Best Validation Loss: 0.0023
Run 003 | Training Loss: 0.0010
Run 003 | Best Validation Loss: 0.0022
Run 004 | Training Loss: 0.0009
Run 004 | Best Validation Loss: 0.0022
Run 005 | Training Loss: 0.0008
Run 005 | Best Validation Loss: 0.0022
Run 006 | Training Loss: 0.0008
Run 006 | Best Validation Loss: 0.0022
Run 007 | Training Loss: 0.0008
Run 007 | Best Validation Loss: 0.0021
Run 008 | Training Loss: 0.0008
Run 008 | Best Validation Loss: 0.0021
Run 009 | Training Loss: 0.0007
Run 009 | Best Validation Loss: 0.0021
Run 010 | Training Loss: 0.0007
Run 010 | Best Validation Loss: 0.0021
Run 011 | Training Loss: 0.0007
Run 011 | Best Validation Loss: 0.0021
Run 012 | Training Loss: 0.0006
Run 012 | Best Validation Loss: 0.0021
Run 013 | Training Loss: 0.0006
Run 013 | Best Validation Loss: 0.0021
Run 014 | Training Loss: 0.0006
Run 014 | Best Validation Loss: 0.0021
Run 015 | Training Loss: 0.0006
Run 015 | Best Validation Loss: 0.0021
Run 016 | Training Loss: 0.0006
Run 016 | Best Validation Loss: 0.0021
Run 017 | Training Loss: 0.0006
Run 017 | Best Validation Loss: 0.0021
Run 018 | Training Loss: 0.0006
Run 018 | Best Validation Loss: 0.0021
Run 019 | Training Loss: 0.0006
Run 019 | Best Validation Loss: 0.0021
Run 020 | Training Loss: 0.0006
Run 020 | Best Validation Loss: 0.0021
Run 021 | Training Loss: 0.0006
Run 021 | Best Validation Loss: 0.0021
mse: 0.02069324904728764
rmse: 0.1438514826037175
mape: 0.29216685343775
rsquared: -0.10491778526361961

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,ddelta,dgamma,...,stock_price,realized_vol,moneyness,impl_volatility,impl_vol_ann,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2002-01-02,2002-01-19,C,105.0,0.2,0.30,34.0,59.0,0.134418,0.057799,...,100.73,0.004923,0.041517,0.183356,0.166383,0,0.020693,0.143851,0.292167,-0.104918
1,2002-01-02,2002-01-19,C,106.0,0.1,0.15,6.0,260.0,0.078105,0.040581,...,100.73,0.004923,0.050995,0.176133,0.170794,0,0.020693,0.143851,0.292167,-0.104918
2,2002-01-02,2002-01-19,C,90.0,10.5,11.00,0.0,160.0,0.974934,0.009727,...,100.73,0.004923,-0.112634,0.284675,0.332337,0,0.020693,0.143851,0.292167,-0.104918
3,2002-01-02,2002-01-19,C,91.0,9.6,10.00,0.0,30.0,0.957577,0.014793,...,100.73,0.004923,-0.101584,0.293254,0.309126,0,0.020693,0.143851,0.292167,-0.104918
4,2002-01-02,2002-01-19,C,92.0,8.6,9.00,0.0,612.0,0.954278,0.017296,...,100.73,0.004923,-0.090655,0.266864,0.287186,0,0.020693,0.143851,0.292167,-0.104918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166267,2002-12-31,2003-09-20,P,925.0,101.3,101.50,0.0,996.0,-0.553557,0.002103,...,879.82,0.234007,0.050076,0.248388,0.382163,1,0.020693,0.143851,0.292167,-0.104918
166268,2002-12-31,2003-09-20,P,950.0,116.0,116.20,0.0,639.0,-0.607127,0.002091,...,879.82,0.234007,0.076745,0.242036,0.378146,1,0.020693,0.143851,0.292167,-0.104918
166269,2002-12-31,2003-09-20,P,975.0,132.2,132.40,0.0,1256.0,-0.659065,0.002032,...,879.82,0.234007,0.102720,0.236583,0.374529,1,0.020693,0.143851,0.292167,-0.104918
166270,2002-12-31,2003-09-20,P,900.0,88.1,88.30,1.0,1941.0,-0.499880,0.002068,...,879.82,0.234007,0.022677,0.255549,0.386536,1,0.020693,0.143851,0.292167,-0.104918
166271,2002-12-31,2003-09-20,C,1300.0,0.6,0.80,0.0,426.0,0.013810,0.000231,...,879.82,0.234007,0.390402,0.204509,0.333614,1,0.020693,0.143851,0.292167,-0.104918

Price Models

In [11]:
# XGBoost modelling option price
set_seed(42)
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['price']

output_xgb_price, importance_xgb_price = XGB_function(data, selected_columns_x, selected_columns_y, params=params_xgb_price, compute_importance=True)
output_xgb_price = output_xgb_price.rename(columns={"output_xgb":"price_xgb"})
output_xgb_price

mse: 195.66627502441406
rmse: 13.988076173098788
mape: 0.3618861734867096
rsquared: 0.9787154197692871
  Feature importance computed

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,impl_volatility,ddelta,...,stock_price,realized_vol,moneyness,price,price_xgb,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2002-01-02,2002-01-19,C,105.0,0.2,0.30,34.0,59.0,0.183356,0.134418,...,100.73,0.004923,0.041517,0.250,0.506912,0,195.666275,13.988076,0.361886,0.978715
1,2002-01-02,2002-01-19,C,106.0,0.1,0.15,6.0,260.0,0.176133,0.078105,...,100.73,0.004923,0.050995,0.125,0.181007,0,195.666275,13.988076,0.361886,0.978715
2,2002-01-02,2002-01-19,C,90.0,10.5,11.00,0.0,160.0,0.284675,0.974934,...,100.73,0.004923,-0.112634,10.750,11.365326,0,195.666275,13.988076,0.361886,0.978715
3,2002-01-02,2002-01-19,C,91.0,9.6,10.00,0.0,30.0,0.293254,0.957577,...,100.73,0.004923,-0.101584,9.800,10.234215,0,195.666275,13.988076,0.361886,0.978715
4,2002-01-02,2002-01-19,C,92.0,8.6,9.00,0.0,612.0,0.266864,0.954278,...,100.73,0.004923,-0.090655,8.800,9.219738,0,195.666275,13.988076,0.361886,0.978715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166267,2002-12-31,2003-09-20,P,925.0,101.3,101.50,0.0,996.0,0.248388,-0.553557,...,879.82,0.234007,0.050076,101.400,133.029755,1,195.666275,13.988076,0.361886,0.978715
166268,2002-12-31,2003-09-20,P,950.0,116.0,116.20,0.0,639.0,0.242036,-0.607127,...,879.82,0.234007,0.076745,116.100,146.144089,1,195.666275,13.988076,0.361886,0.978715
166269,2002-12-31,2003-09-20,P,975.0,132.2,132.40,0.0,1256.0,0.236583,-0.659065,...,879.82,0.234007,0.102720,132.300,161.585312,1,195.666275,13.988076,0.361886,0.978715
166270,2002-12-31,2003-09-20,P,900.0,88.1,88.30,1.0,1941.0,0.255549,-0.499880,...,879.82,0.234007,0.022677,88.200,120.263580,1,195.666275,13.988076,0.361886,0.978715
166271,2002-12-31,2003-09-20,C,1300.0,0.6,0.80,0.0,426.0,0.204509,0.013810,...,879.82,0.234007,0.390402,0.700,9.159775,1,195.666275,13.988076,0.361886,0.978715

In [7]:
# Torch ANN with lbfgs modelling option price
set_seed(42)
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['price']

ignore = ["cp_flag_one"]
output_ann_price_lbfgs = ANN_function_torch_LBFGS(data, selected_columns_x, selected_columns_y, ignore, log_y=True, params=params_lbfgs_price, compute_importance=False)
output_ann_price_lbfgs = output_ann_price_lbfgs.rename(columns={"output_ann":"price_ann"})

C:\Users\chril\AppData\Local\Temp\ipykernel_14936\4038091348.py:129: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:209.)
  Y_val_t = torch.as_tensor(Y_val_ivol_std.values, device=device, dtype=torch.float32)

Run 000 | Training Loss: 12.6979
Run 000 | Best Validation Loss: 0.1281
Run 001 | Training Loss: 0.0798
Run 001 | Best Validation Loss: 0.1005
Run 002 | Training Loss: 0.0541
Run 002 | Best Validation Loss: 0.0968
Run 003 | Training Loss: 0.0491
Run 003 | Best Validation Loss: 0.0949
Run 004 | Training Loss: 0.0470
Run 004 | Best Validation Loss: 0.0910
Run 005 | Training Loss: 0.0448
Run 005 | Best Validation Loss: 0.0874
Run 006 | Training Loss: 0.0427
Run 006 | Best Validation Loss: 0.0774
Run 007 | Training Loss: 0.0395
Run 007 | Best Validation Loss: 0.0770
Run 008 | Training Loss: 0.0354
Run 008 | Best Validation Loss: 0.0575
Run 009 | Training Loss: 0.0309
Run 009 | Best Validation Loss: 0.0532
Run 010 | Training Loss: 0.0273
Run 010 | Best Validation Loss: 0.0530
Run 011 | Training Loss: 0.0251
Run 011 | Best Validation Loss: 0.0495
Run 012 | Training Loss: 0.0235
Run 012 | Best Validation Loss: 0.0495
Run 013 | Training Loss: 0.0219
Run 013 | Best Validation Loss: 0.0495
Run 014 | Training Loss: 0.0209
Run 014 | Best Validation Loss: 0.0495
Run 015 | Training Loss: 0.0201
Run 015 | Best Validation Loss: 0.0479
Run 016 | Training Loss: 0.0192
Run 016 | Best Validation Loss: 0.0478
Run 017 | Training Loss: 0.0185
Run 017 | Best Validation Loss: 0.0478
Run 018 | Training Loss: 0.0173
Run 018 | Best Validation Loss: 0.0428
Run 019 | Training Loss: 0.0165
Run 019 | Best Validation Loss: 0.0399
Run 020 | Training Loss: 0.0159
Run 020 | Best Validation Loss: 0.0394
Run 021 | Training Loss: 0.0153
Run 021 | Best Validation Loss: 0.0385
Run 022 | Training Loss: 0.0147
Run 022 | Best Validation Loss: 0.0385
Run 023 | Training Loss: 0.0143
Run 023 | Best Validation Loss: 0.0375
Run 024 | Training Loss: 0.0139
Run 024 | Best Validation Loss: 0.0375
Run 025 | Training Loss: 0.0136
Run 025 | Best Validation Loss: 0.0375
Run 026 | Training Loss: 0.0133
Run 026 | Best Validation Loss: 0.0375
Run 027 | Training Loss: 0.0130
Run 027 | Best Validation Loss: 0.0375
Run 028 | Training Loss: 0.0128
Run 028 | Best Validation Loss: 0.0375
Run 029 | Training Loss: 0.0125
Run 029 | Best Validation Loss: 0.0375
Run 030 | Training Loss: 0.0122
Run 030 | Best Validation Loss: 0.0375
Run 031 | Training Loss: 0.0119
Run 031 | Best Validation Loss: 0.0375
Run 032 | Training Loss: 0.0117
Run 032 | Best Validation Loss: 0.0375
Run 033 | Training Loss: 0.0115
Run 033 | Best Validation Loss: 0.0368
Run 034 | Training Loss: 0.0114
Run 034 | Best Validation Loss: 0.0368
Run 035 | Training Loss: 0.0112
Run 035 | Best Validation Loss: 0.0368
Run 036 | Training Loss: 0.0111
Run 036 | Best Validation Loss: 0.0368
Run 037 | Training Loss: 0.0111
Run 037 | Best Validation Loss: 0.0368
Run 038 | Training Loss: 0.0110
Run 038 | Best Validation Loss: 0.0368
Run 039 | Training Loss: 0.0108
Run 039 | Best Validation Loss: 0.0368
Run 040 | Training Loss: 0.0107
Run 040 | Best Validation Loss: 0.0368
Run 041 | Training Loss: 0.0106
Run 041 | Best Validation Loss: 0.0368
Run 042 | Training Loss: 0.0105
Run 042 | Best Validation Loss: 0.0368
Run 043 | Training Loss: 0.0104
Run 043 | Best Validation Loss: 0.0368
Run 044 | Training Loss: 0.0103
Run 044 | Best Validation Loss: 0.0368
Run 045 | Training Loss: 0.0101
Run 045 | Best Validation Loss: 0.0368
Run 046 | Training Loss: 0.0099
Run 046 | Best Validation Loss: 0.0368
Run 047 | Training Loss: 0.0097
Run 047 | Best Validation Loss: 0.0363
Run 048 | Training Loss: 0.0096
Run 048 | Best Validation Loss: 0.0363
Run 049 | Training Loss: 0.0095
Run 049 | Best Validation Loss: 0.0363
mse: 666.3816534188254
rmse: 25.814369126880194
mape: 0.767681025176011
rsquared: 0.9275110585949263

Volatility Surface Estimation

In [6]:
##### AGBoost ML calibration and estimation functions:

def XGB_function_surface(data, x_cols, y_cols, params=None):
    
    X, Y = data[x_cols].copy(), data[y_cols].copy()

    label_encoders_ivol = {}
    categorical_columns = []
    for col in categorical_columns:
        label_encoder = LabelEncoder()
        X[col] = label_encoder.fit_transform(X[col])
        label_encoders_ivol[col] = label_encoder

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size= 0.7, shuffle = True, random_state = 0)
    
    X_train_encoded_ivol = X_train
    X_test_encoded_ivol = X_test
    Y_train_ivol = Y_train
    Y_test_ivol = Y_test


    _p = params or {}
    model_xgb_ivol = xgboost.XGBRegressor(
        gamma         = _p.get('gamma',         1),
        learning_rate = _p.get('learning_rate', 0.1),
        max_depth     = _p.get('max_depth',     20),
        n_estimators  = _p.get('n_estimators',  200),
        subsample     = _p.get('subsample',     1),
        reg_lambda    = _p.get('reg_lambda',    1),
        eval_metric='rmse', tree_method='hist', device='cuda',
    )

    model_xgb_ivol.fit(X_train_encoded_ivol, Y_train_ivol, verbose = False, eval_set = [(X_test_encoded_ivol, Y_test_ivol)])

    y_pred_xgb_ivol = model_xgb_ivol.predict(X_test_encoded_ivol)
    y_pred_xgb_ivol_train = model_xgb_ivol.predict(X_train_encoded_ivol)

    rmse_xgb_ivol = np.sqrt(mean_squared_error(Y_test_ivol, y_pred_xgb_ivol))
    mse_xgb_ivol = mean_squared_error(Y_test_ivol, y_pred_xgb_ivol)
    mape_xgb_ivol = mean_absolute_percentage_error(Y_test_ivol, y_pred_xgb_ivol)
    rsquared_xgb_ivol = r2_score(Y_test_ivol, y_pred_xgb_ivol)


    print("mse:", mse_xgb_ivol)
    print("rmse:", rmse_xgb_ivol)
    print("mape:", mape_xgb_ivol)
    print("rsquared:", rsquared_xgb_ivol)


    for col in categorical_columns:
        X_test_encoded_ivol[col] = label_encoders_ivol[col].inverse_transform(X_test_encoded_ivol[col])
        X_train_encoded_ivol[col] = label_encoders_ivol[col].inverse_transform(X_train_encoded_ivol[col])


    output_xgb_ivol = pd.concat([X_test_encoded_ivol, 
                                 Y_test_ivol.set_axis(X_test_encoded_ivol.index), 
                                 pd.DataFrame(y_pred_xgb_ivol, columns = ["output_xgb"]).set_axis(X_test_encoded_ivol.index)], axis=1)
    output_xgb_ivol_train = pd.concat([X_train_encoded_ivol, 
                                      Y_train_ivol.set_axis(X_train_encoded_ivol.index), 
                                      pd.DataFrame(y_pred_xgb_ivol_train, columns = ["output_xgb"]).set_axis(X_train_encoded_ivol.index)], axis=1)

    output_xgb_ivol["out_of_sample"] = 1
    output_xgb_ivol_train["out_of_sample"] = 0

    output_xgb_ivol_full = pd.concat([output_xgb_ivol_train, output_xgb_ivol], axis = 0)

    data_clean = data.drop(columns = [col for col in data.columns if col in output_xgb_ivol_full.columns])
    data_out = pd.concat([data_clean, output_xgb_ivol_full], axis = 1)

    data_out["mse_optim"] = mse_xgb_ivol
    data_out["rmse_optim"] = rmse_xgb_ivol
    data_out["mape_optim"] = mape_xgb_ivol
    data_out["rsquared_optim"] = rsquared_xgb_ivol

    return(data_out)

In [7]:
# Group data on day and cusip (underlying)
set_seed(42)
grouped_data = data.groupby(['date'])
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['impl_volatility']

streams = {}
results = {}
for i, group in grouped_data:
    streams[i] = torch.cuda.Stream()
    results[i] = torch.empty(1,device="cuda")

for i, group in grouped_data:
    stream = streams[i]
    with torch.cuda.stream(stream):
        print(group["date"].unique())
        
        temp = XGB_function_surface(group, selected_columns_x, selected_columns_y, params=params_xgb_surface_ivol)
        results[i] = temp.copy()
    del temp, group
    torch.cuda.synchronize()
    torch.cuda.empty_cache()


for stream in streams.values():
    stream.synchronize()

surface_xgb_ivol_data = pd.concat(results.values())
surface_xgb_ivol_data

_oos = surface_xgb_ivol_data[surface_xgb_ivol_data["out_of_sample"] == 1]
print("explained variance score:", explained_variance_score(np.array(np.exp(_oos["impl_volatility"])-1), _oos["output_xgb"]))
print("mse:", mean_squared_error(_oos["impl_volatility"], _oos["output_xgb"]))
print("rmse:", np.sqrt(mean_squared_error(_oos["impl_volatility"], _oos["output_xgb"])))
print("mape:", mean_absolute_percentage_error(_oos["impl_volatility"], _oos["output_xgb"]))
print("rsquared:", r2_score(_oos["impl_volatility"], _oos["output_xgb"]))

surface_xgb_ivol_data = surface_xgb_ivol_data.rename(columns={"output_xgb":"impl_vol_xgb"})
surface_xgb_ivol_data

<DatetimeArray>
['2003-01-02 00:00:00']
Length: 1, dtype: datetime64[ms]

c:\Users\chril\torch_gpu\Lib\site-packages\xgboost\core.py:751: UserWarning: [16:37:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

mse: 0.0004646865709219128
rmse: 0.021556589965064345
mape: 0.03863424062728882
rsquared: 0.9549427628517151
<DatetimeArray>
['2003-01-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002547635813243687
rmse: 0.015961315150211423
mape: 0.03459857776761055
rsquared: 0.9756075739860535
<DatetimeArray>
['2003-01-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000237670901697129
rmse: 0.015416578793530327
mape: 0.03210277482867241
rsquared: 0.9711090922355652
<DatetimeArray>
['2003-01-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00041184647125191987
rmse: 0.020294000868530577
mape: 0.03296791389584541
rsquared: 0.9670687317848206
<DatetimeArray>
['2003-01-08 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00020458016660995781
rmse: 0.014303152331215584
mape: 0.029570432379841805
rsquared: 0.979239284992218
<DatetimeArray>
['2003-01-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000355210795532912
rmse: 0.018847036783879636
mape: 0.03192781284451485
rsquared: 0.959396481513977
<DatetimeArray>
['2003-01-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005553109222091734
rmse: 0.023565036011200437
mape: 0.03415242210030556
rsquared: 0.9665432572364807
<DatetimeArray>
['2003-01-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00021732403547503054
rmse: 0.014741914240526247
mape: 0.025625059381127357
rsquared: 0.9748767018318176
<DatetimeArray>
['2003-01-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002902531996369362
rmse: 0.017036818941250042
mape: 0.032096173614263535
rsquared: 0.9697787761688232
<DatetimeArray>
['2003-01-15 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002694316499400884
rmse: 0.01641437327283891
mape: 0.03177341818809509
rsquared: 0.9763646125793457
<DatetimeArray>
['2003-01-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0006557274027727544
rmse: 0.025607174829972056
mape: 0.030382506549358368
rsquared: 0.9480093121528625
<DatetimeArray>
['2003-01-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00024066910555120558
rmse: 0.015513513642988992
mape: 0.03297791630029678
rsquared: 0.9767416715621948
<DatetimeArray>
['2003-01-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00025246062432415783
rmse: 0.01588900954509619
mape: 0.029408510774374008
rsquared: 0.9689184427261353
<DatetimeArray>
['2003-01-22 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00020464583940338343
rmse: 0.014305447892442355
mape: 0.02708427980542183
rsquared: 0.9686799049377441
<DatetimeArray>
['2003-01-23 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00038153026252985
rmse: 0.019532799659287198
mape: 0.03302159532904625
rsquared: 0.9596211910247803
<DatetimeArray>
['2003-01-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0008516708039678633
rmse: 0.02918339945873104
mape: 0.025949683040380478
rsquared: 0.9151384830474854
<DatetimeArray>
['2003-01-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0008626946364529431
rmse: 0.029371663835284223
mape: 0.024205783382058144
rsquared: 0.9224718809127808
<DatetimeArray>
['2003-01-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0006827645120210946
rmse: 0.026129762953786904
mape: 0.02924375981092453
rsquared: 0.9443377256393433
<DatetimeArray>
['2003-01-29 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00023881724337115884
rmse: 0.015453712931563043
mape: 0.028591156005859375
rsquared: 0.9639937877655029
<DatetimeArray>
['2003-01-30 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003456018166616559
rmse: 0.018590368922150415
mape: 0.029966723173856735
rsquared: 0.960861086845398
<DatetimeArray>
['2003-01-31 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0010052123107016087
rmse: 0.03170508335743038
mape: 0.02987203747034073
rsquared: 0.8891753554344177
<DatetimeArray>
['2003-02-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003170166746713221
rmse: 0.017804962080030445
mape: 0.02521897852420807
rsquared: 0.962024986743927
<DatetimeArray>
['2003-02-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00021034861856605858
rmse: 0.01450340024153159
mape: 0.023621218279004097
rsquared: 0.9720247387886047
<DatetimeArray>
['2003-02-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00044982085819356143
rmse: 0.02120898060241372
mape: 0.027399200946092606
rsquared: 0.9446551203727722
<DatetimeArray>
['2003-02-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0001790290407370776
rmse: 0.013380173419544217
mape: 0.023740122094750404
rsquared: 0.9815457463264465
<DatetimeArray>
['2003-02-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005213703843764961
rmse: 0.022833536396635892
mape: 0.03136022761464119
rsquared: 0.935214638710022
<DatetimeArray>
['2003-02-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0006200899952091277
rmse: 0.024901606277690756
mape: 0.026568321511149406
rsquared: 0.9379552006721497
<DatetimeArray>
['2003-02-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00031995028257369995
rmse: 0.017887154121707008
mape: 0.024001535028219223
rsquared: 0.955571174621582
<DatetimeArray>
['2003-02-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0007927442784421146
rmse: 0.028155714845162688
mape: 0.02938186191022396
rsquared: 0.9575350880622864
<DatetimeArray>
['2003-02-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0010517872869968414
rmse: 0.03243127020325971
mape: 0.037638481706380844
rsquared: 0.9424514770507812
<DatetimeArray>
['2003-02-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.006612459663301706
rmse: 0.08131703181561478
mape: 0.042796142399311066
rsquared: 0.8219236731529236
<DatetimeArray>
['2003-02-18 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00014237198047339916
rmse: 0.011931973033551457
mape: 0.024092771112918854
rsquared: 0.9816569685935974
<DatetimeArray>
['2003-02-19 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000422556942794472
rmse: 0.020556189890017847
mape: 0.021989287808537483
rsquared: 0.9604294300079346
<DatetimeArray>
['2003-02-20 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0004547679563984275
rmse: 0.02132528912813206
mape: 0.028697820380330086
rsquared: 0.9573631286621094
<DatetimeArray>
['2003-02-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000565773923881352
rmse: 0.023786002688164144
mape: 0.030843626707792282
rsquared: 0.9617151021957397
<DatetimeArray>
['2003-02-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0001989912852877751
rmse: 0.014106427091498935
mape: 0.02870478853583336
rsquared: 0.9719860553741455
<DatetimeArray>
['2003-02-25 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00030512060038745403
rmse: 0.017467701634372338
mape: 0.024909289553761482
rsquared: 0.9741250276565552
<DatetimeArray>
['2003-02-26 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0013112161541357636
rmse: 0.03621071877408351
mape: 0.029363902285695076
rsquared: 0.8581271767616272
<DatetimeArray>
['2003-02-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003849745262414217
rmse: 0.019620767728134945
mape: 0.027832387015223503
rsquared: 0.9491774439811707
<DatetimeArray>
['2003-02-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003790049231611192
rmse: 0.019468048776421307
mape: 0.027813304215669632
rsquared: 0.9599640369415283
<DatetimeArray>
['2003-03-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0004090769507456571
rmse: 0.02022565081142402
mape: 0.02494135871529579
rsquared: 0.9523594379425049
<DatetimeArray>
['2003-03-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00015425443416461349
rmse: 0.01241992085983697
mape: 0.022771216928958893
rsquared: 0.9797621965408325
<DatetimeArray>
['2003-03-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005590216023847461
rmse: 0.023643637672421433
mape: 0.031959813088178635
rsquared: 0.9755567908287048
<DatetimeArray>
['2003-03-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00022824149345979095
rmse: 0.015107663401724005
mape: 0.024619130417704582
rsquared: 0.9693365693092346
<DatetimeArray>
['2003-03-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00042490410851314664
rmse: 0.020613202286717768
mape: 0.028003735467791557
rsquared: 0.9605417847633362
<DatetimeArray>
['2003-03-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0017013940960168839
rmse: 0.041247958689090106
mape: 0.029896048828959465
rsquared: 0.8603903651237488
<DatetimeArray>
['2003-03-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00038772300467826426
rmse: 0.01969068319480724
mape: 0.023148957639932632
rsquared: 0.9910495281219482
<DatetimeArray>
['2003-03-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.002136716851964593
rmse: 0.046224634687194587
mape: 0.02431231550872326
rsquared: 0.9190260767936707
<DatetimeArray>
['2003-03-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0017413556342944503
rmse: 0.04172955348783941
mape: 0.0276817474514246
rsquared: 0.9101775884628296
<DatetimeArray>
['2003-03-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.001225225511007011
rmse: 0.035003221437562154
mape: 0.035173214972019196
rsquared: 0.9713624119758606
<DatetimeArray>
['2003-03-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00018465389439370483
rmse: 0.013588741457313288
mape: 0.025759520009160042
rsquared: 0.9668939709663391
<DatetimeArray>
['2003-03-18 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00033892507781274617
rmse: 0.018409917919772107
mape: 0.024817105382680893
rsquared: 0.9673877954483032
<DatetimeArray>
['2003-03-19 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000495426298584789
rmse: 0.022258173747744647
mape: 0.03269417583942413
rsquared: 0.9197240471839905
<DatetimeArray>
['2003-03-20 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00018461240688338876
rmse: 0.013587214831722826
mape: 0.024726606905460358
rsquared: 0.9752759337425232
<DatetimeArray>
['2003-03-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0001655566884437576
rmse: 0.012866883400565873
mape: 0.02884260006248951
rsquared: 0.9715143442153931
<DatetimeArray>
['2003-03-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002585020265541971
rmse: 0.016077998213527612
mape: 0.02303702011704445
rsquared: 0.9624531865119934
<DatetimeArray>
['2003-03-25 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005360104260034859
rmse: 0.02315189897186591
mape: 0.030578801408410072
rsquared: 0.9061990976333618
<DatetimeArray>
['2003-03-26 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0004147870058659464
rmse: 0.020366320381108277
mape: 0.028683630749583244
rsquared: 0.9417634606361389
<DatetimeArray>
['2003-03-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00010295387619407848
rmse: 0.010146618953822918
mape: 0.02301083132624626
rsquared: 0.9793592095375061
<DatetimeArray>
['2003-03-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0010918753687292337
rmse: 0.033043537472995134
mape: 0.025538349524140358
rsquared: 0.8536101579666138
<DatetimeArray>
['2003-03-31 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0013215369544923306
rmse: 0.03635294973578252
mape: 0.03363762050867081
rsquared: 0.8341426253318787
<DatetimeArray>
['2003-04-01 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005333554581739008
rmse: 0.023094489779466893
mape: 0.03143011033535004
rsquared: 0.9130153059959412
<DatetimeArray>
['2003-04-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00015937391435727477
rmse: 0.012624338175020296
mape: 0.029216226190328598
rsquared: 0.9694725275039673
<DatetimeArray>
['2003-04-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.002150188200175762
rmse: 0.046370121847756254
mape: 0.037482090294361115
rsquared: 0.7509875297546387
<DatetimeArray>
['2003-04-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0008397889323532581
rmse: 0.02897911200077149
mape: 0.028537500649690628
rsquared: 0.8796123266220093
<DatetimeArray>
['2003-04-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003183734661433846
rmse: 0.01784302289813541
mape: 0.03129800781607628
rsquared: 0.9497304558753967
<DatetimeArray>
['2003-04-08 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0008188002975657582
rmse: 0.028614686745896036
mape: 0.032556574791669846
rsquared: 0.9562639594078064
<DatetimeArray>
['2003-04-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0008519837283529341
rmse: 0.02918876030860054
mape: 0.030921241268515587
rsquared: 0.9583783745765686
<DatetimeArray>
['2003-04-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0015995721332728863
rmse: 0.03999465130830479
mape: 0.03358621895313263
rsquared: 0.8976503610610962
<DatetimeArray>
['2003-04-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.001046406221576035
rmse: 0.0323482027565062
mape: 0.037202008068561554
rsquared: 0.9166628122329712
<DatetimeArray>
['2003-04-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 7.107839337550104e-05
rmse: 0.00843080028084529
mape: 0.022679930552840233
rsquared: 0.9832630753517151
<DatetimeArray>
['2003-04-15 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0010698934784159064
rmse: 0.03270922619714362
mape: 0.038789767771959305
rsquared: 0.8976765275001526
<DatetimeArray>
['2003-04-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00021117215510457754
rmse: 0.014531763661186399
mape: 0.029711389914155006
rsquared: 0.9540999531745911
<DatetimeArray>
['2003-04-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0004325391200836748
rmse: 0.020797574860633987
mape: 0.03590167686343193
rsquared: 0.9268680214881897
<DatetimeArray>
['2003-04-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003284000849816948
rmse: 0.018121812408854
mape: 0.03208541125059128
rsquared: 0.9623388051986694
<DatetimeArray>
['2003-04-22 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0009275009506382048
rmse: 0.030454900272997198
mape: 0.044734276831150055
rsquared: 0.8597846031188965
<DatetimeArray>
['2003-04-23 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0018143659690394998
rmse: 0.04259537497240164
mape: 0.05148127302527428
rsquared: 0.6812005043029785
<DatetimeArray>
['2003-04-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005163869936950505
rmse: 0.02272415001039754
mape: 0.03806859999895096
rsquared: 0.8837085366249084
<DatetimeArray>
['2003-04-25 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00028220887179486454
rmse: 0.016799073539777856
mape: 0.03615444526076317
rsquared: 0.9322314858436584
<DatetimeArray>
['2003-04-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000922112783882767
rmse: 0.030366310014270207
mape: 0.043356627225875854
rsquared: 0.8114895820617676
<DatetimeArray>
['2003-04-29 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0009257841156795621
rmse: 0.03042670070315811
mape: 0.03526151552796364
rsquared: 0.8464186191558838
<DatetimeArray>
['2003-04-30 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0012207479448989034
rmse: 0.03493920355272718
mape: 0.03634926304221153
rsquared: 0.7971351146697998
<DatetimeArray>
['2003-05-01 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.002267660805955529
rmse: 0.047619962263272836
mape: 0.04036965221166611
rsquared: 0.7560322284698486
<DatetimeArray>
['2003-05-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.011279009282588959
rmse: 0.10620268020435718
mape: 0.06306547671556473
rsquared: 0.5418494939804077
<DatetimeArray>
['2003-05-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005768907140009105
rmse: 0.02401854937336788
mape: 0.04039144888520241
rsquared: 0.8666821122169495
<DatetimeArray>
['2003-05-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000637516553979367
rmse: 0.025249090161417045
mape: 0.04043272137641907
rsquared: 0.9173327088356018
<DatetimeArray>
['2003-05-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.005162453278899193
rmse: 0.07185021418826247
mape: 0.04709590971469879
rsquared: 0.5972291231155396
<DatetimeArray>
['2003-05-08 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002999651769641787
rmse: 0.01731950279206013
mape: 0.038537025451660156
rsquared: 0.9458437561988831
<DatetimeArray>
['2003-05-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0012023999588564038
rmse: 0.03467563927105604
mape: 0.044761765748262405
rsquared: 0.8347423672676086
<DatetimeArray>
['2003-05-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00012867180339526385
rmse: 0.01134335944045078
mape: 0.03157701715826988
rsquared: 0.9723975658416748
<DatetimeArray>
['2003-05-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0001322365424130112
rmse: 0.011499414872636398
mape: 0.031140940263867378
rsquared: 0.9699877500534058
<DatetimeArray>
['2003-05-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00010915674647549167
rmse: 0.010447810606796606
mape: 0.02892562747001648
rsquared: 0.9802197217941284
<DatetimeArray>
['2003-05-15 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 9.344916179543361e-05
rmse: 0.009666910664500506
mape: 0.02920805849134922
rsquared: 0.9755272269248962
<DatetimeArray>
['2003-05-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00015025002358015627
rmse: 0.012257651633985862
mape: 0.03500114008784294
rsquared: 0.9639327526092529
<DatetimeArray>
['2003-05-19 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000178575050085783
rmse: 0.013363197599593557
mape: 0.032595887780189514
rsquared: 0.9730595350265503
<DatetimeArray>
['2003-05-20 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002365686814300716
rmse: 0.015380789363035682
mape: 0.0333305224776268
rsquared: 0.9611515998840332
<DatetimeArray>
['2003-05-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002511150960344821
rmse: 0.015846611500080456
mape: 0.031018532812595367
rsquared: 0.9577420949935913
<DatetimeArray>
['2003-05-22 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00040185064426623285
rmse: 0.020046212716277177
mape: 0.03270528465509415
rsquared: 0.9215629696846008
<DatetimeArray>
['2003-05-23 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003537680604495108
rmse: 0.018808722988270916
mape: 0.04130265489220619
rsquared: 0.935221791267395
<DatetimeArray>
['2003-05-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0003163543588016182
rmse: 0.017786353161950267
mape: 0.03297784924507141
rsquared: 0.9766784310340881
<DatetimeArray>
['2003-05-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00017233651306014508
rmse: 0.013127700219769839
mape: 0.036312200129032135
rsquared: 0.9733177423477173
<DatetimeArray>
['2003-05-29 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00021861230197828263
rmse: 0.014785543682201295
mape: 0.03450366109609604
rsquared: 0.9682165384292603
<DatetimeArray>
['2003-05-30 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0002372768212808296
rmse: 0.015403792431762693
mape: 0.029579712077975273
rsquared: 0.9661678671836853
<DatetimeArray>
['2003-06-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.013890882022678852
rmse: 0.11785958604491555
mape: 0.0544486828148365
rsquared: 0.589980959892273
<DatetimeArray>
['2003-06-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.000827917770948261
rmse: 0.028773560275855002
mape: 0.0338260717689991
rsquared: 0.9521878957748413
<DatetimeArray>
['2003-06-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0007560303201898932
rmse: 0.027496005531529363
mape: 0.034758806228637695
rsquared: 0.931387186050415
<DatetimeArray>
['2003-06-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.012580595910549164
rmse: 0.1121632556167534
mape: 0.05549817904829979
rsquared: 0.358970582485199
<DatetimeArray>
['2003-06-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.00017796781321521848
rmse: 0.013340457758833408
mape: 0.02994840033352375
rsquared: 0.9634478092193604
<DatetimeArray>
['2003-06-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.0005923878052271903
rmse: 0.024339018164814912
mape: 0.03164360672235489
rsquared: 0.9618036150932312
<DatetimeArray>
['2003-06-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 0.018362848088145256
rmse: 0.1355095867019941
mape: 0.05827334150671959
rsquared: 0.6470094919204712
<DatetimeArray>
['2003-06-11 00:00:00']

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,ddelta,dgamma,...,stock_price,realized_vol,moneyness,impl_volatility,impl_vol_xgb,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2003-01-02,2003-02-22,C,90.0,1.30,1.50,1464.0,5083.0,0.309251,0.047734,...,86.08,0.030519,0.044533,0.233642,0.230018,0,0.000465,0.021557,0.038634,0.954943
1,2003-01-02,2003-02-22,C,91.0,0.95,1.15,255.0,540.0,0.256302,0.045347,...,86.08,0.030519,0.055582,0.224751,0.230018,1,0.000465,0.021557,0.038634,0.954943
2,2003-01-02,2003-02-22,C,92.0,0.75,0.95,0.0,355.0,0.216934,0.041150,...,86.08,0.030519,0.066511,0.225981,0.230018,1,0.000465,0.021557,0.038634,0.954943
3,2003-01-02,2003-02-22,C,94.0,0.40,0.55,0.0,835.0,0.139982,0.032262,...,86.08,0.030519,0.088018,0.218488,0.223365,0,0.000465,0.021557,0.038634,0.954943
4,2003-01-02,2003-03-22,C,90.0,2.15,2.45,2028.0,13151.0,0.361403,0.037649,...,86.08,0.048298,0.044533,0.250788,0.241419,0,0.000465,0.021557,0.038634,0.954943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163837,2003-12-31,2004-09-18,P,975.0,20.10,22.10,0.0,744.0,-0.191240,0.001474,...,1111.92,0.093558,-0.131406,0.196156,0.201530,1,0.000180,0.013406,0.037532,0.942798
163838,2003-12-31,2004-09-18,P,995.0,23.50,25.50,607.0,4679.0,-0.220435,0.001657,...,1111.92,0.093558,-0.111101,0.189753,0.192857,0,0.000180,0.013406,0.037532,0.942798
163839,2003-12-31,2004-09-18,P,900.0,11.50,13.10,3150.0,4822.0,-0.111764,0.000908,...,1111.92,0.093558,-0.211449,0.222397,0.234245,1,0.000180,0.013406,0.037532,0.942798
163840,2003-12-31,2004-03-20,P,1500.0,387.50,389.50,0.0,13601.0,-0.986928,0.000187,...,1111.92,0.023402,0.299377,0.270825,0.152293,1,0.000180,0.013406,0.037532,0.942798
163841,2003-12-31,2004-06-19,P,1500.0,387.20,389.20,0.0,326.0,-0.979654,0.000230,...,1111.92,0.059106,0.299377,0.193454,0.152293,1,0.000180,0.013406,0.037532,0.942798

In [8]:
##### ANN torch calibration and estimation function with code data pipeline correction:
def ANN_function_torch_LBFGS_surface(data, x_cols, y_cols, ignore, batch = 2048, log_y = False, params=None):

    X, Y = data[x_cols].copy(), data[y_cols].copy()
    
    label_encoders_ivol = {}
    categorical_columns = []
    for col in categorical_columns:
        label_encoder = LabelEncoder()
        X[col] = label_encoder.fit_transform(X[col])
        label_encoders_ivol[col] = label_encoder

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size= 0.7, shuffle = True, random_state = 0)


    scaler_X_ivol = StandardScaler()

    non_categ_cols_ivol = [col for col in X_train.columns if col not in ignore]
    X_train_encoded_ivol_std = X_train.copy()
    X_test_encoded_ivol_std = X_test.copy()
    X_train_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.fit_transform(X_train_encoded_ivol_std[non_categ_cols_ivol])
    X_test_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.transform(X_test_encoded_ivol_std[non_categ_cols_ivol])

    if log_y:
        Y_train_ivol_std = np.log(Y_train)
        Y_test_ivol_std  = np.log(Y_test)
    else:
        Y_train_ivol_std = Y_train
        Y_test_ivol_std  = Y_test


    _p           = params or {}
    n_layers     = _p.get('n_layers',     3)
    n_units      = _p.get('n_units',      64)
    max_iter     = _p.get('max_iter',     20)
    history_size = _p.get('history_size', 1)


    class MLP(nn.Module):
        def __init__(self, n_features):
            super().__init__()
            layers = [nn.Linear(n_features, n_units), nn.GELU()]
            for _ in range(n_layers - 1):
                layers += [nn.Linear(n_units, n_units), nn.GELU()]
            layers.append(nn.Linear(n_units, 1))
            self.net = nn.Sequential(*layers)

        def forward(self, x):
            return self.net(x) if log_y else torch.nn.functional.softplus(self.net(x))

    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")


    model = MLP(len(X_train_encoded_ivol_std.columns)).to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.LBFGS(
        model.parameters(),
        max_iter=max_iter,
        history_size=history_size,
        line_search_fn="strong_wolfe"
    )

    model.train()
    n = len(X_train_encoded_ivol_std)


    for i in range(0, n, batch):
        end = min(i + batch, n)
        xb = torch.as_tensor(X_train_encoded_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)
        yb = torch.as_tensor(Y_train_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)

        def closure():
            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()
            return loss
        
        for ii in range(5):
            total_loss = 0
            loss_temp = optimizer.step(closure)

            total_loss += loss_temp



            print(f"Run {ii:03d} | Training Loss: {total_loss:.4f}")
    

    model.eval()
    with torch.no_grad():
        
        X_test_encoded_ivol_std_t = torch.from_numpy(X_test_encoded_ivol_std.values.astype(np.float32)).to(device)
        X_train_encoded_ivol_std_t = torch.from_numpy(X_train_encoded_ivol_std.values.astype(np.float32)).to(device)
        y_pred_ann_ivol = model(X_test_encoded_ivol_std_t).cpu().numpy()
        y_pred_ann_ivol_train = model(X_train_encoded_ivol_std_t).cpu().numpy()

    if log_y:
        y_pred_ann_ivol       = np.exp(y_pred_ann_ivol)
        y_pred_ann_ivol_train = np.exp(y_pred_ann_ivol_train)

    rmse_ann_ivol = np.sqrt(mean_squared_error(Y_test.values.ravel(), y_pred_ann_ivol))
    mse_ann_ivol = mean_squared_error(Y_test.values.ravel(), y_pred_ann_ivol)
    mape_ann_ivol = mean_absolute_percentage_error(Y_test.values.ravel(), y_pred_ann_ivol)
    rsquared_ann_ivol = r2_score(Y_test.values.ravel(), y_pred_ann_ivol)


    print("mse:", mse_ann_ivol)
    print("rmse:", rmse_ann_ivol)
    print("mape:", mape_ann_ivol)
    print("rsquared:", rsquared_ann_ivol)


    for col in categorical_columns:
        X_test_encoded_ivol_std[col] = label_encoders_ivol[col].inverse_transform(X_test_encoded_ivol_std[col])
        X_train_encoded_ivol_std[col] = label_encoders_ivol[col].inverse_transform(X_train_encoded_ivol_std[col])

    X_test_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_test_encoded_ivol_std[non_categ_cols_ivol])
    X_train_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_train_encoded_ivol_std[non_categ_cols_ivol])

    if log_y:
        Y_test_ivol_std  = np.exp(Y_test_ivol_std)
        Y_train_ivol_std = np.exp(Y_train_ivol_std)

    output_ann_ivol = pd.concat([X_test_encoded_ivol_std, 
                                 Y_test_ivol_std.set_axis(X_test_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol, columns = ["output_ann"]).set_axis(X_test_encoded_ivol_std.index)], axis=1)
    output_ann_ivol_train = pd.concat([X_train_encoded_ivol_std, 
                                 Y_train_ivol_std.set_axis(X_train_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol_train, columns = ["output_ann"]).set_axis(X_train_encoded_ivol_std.index)], axis=1)


    output_ann_ivol["out_of_sample"] = 1
    output_ann_ivol_train["out_of_sample"] = 0

    output_ann_ivol_full = pd.concat([output_ann_ivol_train, output_ann_ivol], axis = 0)

    data_clean = data.drop(columns = [col for col in data.columns if col in output_ann_ivol_full.columns])
    data_out = pd.concat([data_clean, output_ann_ivol_full], axis = 1)

    data_out["mse_optim"] = mse_ann_ivol
    data_out["rmse_optim"] = rmse_ann_ivol
    data_out["mape_optim"] = mape_ann_ivol
    data_out["rsquared_optim"] = rsquared_ann_ivol

    return(data_out)

In [9]:
# Group data on day and cusip (underlying)
set_seed(42)
grouped_data = data.groupby(['date'])
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['impl_volatility']
ignore = ["cp_flag_one"]

streams = {}
results = {}
for i, group in grouped_data:
    streams[i] = torch.cuda.Stream()
    results[i] = torch.empty(1,device="cuda")

for i, group in grouped_data:
    stream = streams[i]
    with torch.cuda.stream(stream):
        print(group["date"].unique())
        
        temp = ANN_function_torch_LBFGS_surface(group, selected_columns_x, selected_columns_y, ignore, params=params_lbfgs_surface_ivol)
        results[i] = temp.copy()
    del temp, group
    torch.cuda.synchronize()
    torch.cuda.empty_cache()


for stream in streams.values():
    stream.synchronize()

surface_ann_lbfgs_ivol_data = pd.concat(results.values())
surface_ann_lbfgs_ivol_data

_oos = surface_ann_lbfgs_ivol_data[surface_ann_lbfgs_ivol_data["out_of_sample"] == 1]
print("mse:", mean_squared_error(_oos["impl_volatility"], _oos["output_ann"]))
print("rmse:", np.sqrt(mean_squared_error(_oos["impl_volatility"], _oos["output_ann"])))
print("mape:", mean_absolute_percentage_error(_oos["impl_volatility"], _oos["output_ann"]))
print("rsquared:", r2_score(_oos["impl_volatility"], _oos["output_ann"]))

surface_ann_lbfgs_ivol_data = surface_ann_lbfgs_ivol_data.rename(columns={"output_ann":"impl_vol_ann"})
surface_ann_lbfgs_ivol_data

<DatetimeArray>
['2003-01-02 00:00:00']
Length: 1, dtype: datetime64[ms]

C:\Users\chril\AppData\Local\Temp\ipykernel_23984\2280421579.py:110: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:209.)
  yb = torch.as_tensor(Y_train_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)

Run 000 | Training Loss: 0.1472
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 8.735742332606544e-05
rmse: 0.009346519316091175
mape: 0.018246218909433957
rsquared: 0.9915295919673706
<DatetimeArray>
['2003-01-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1327
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.6057238657726696e-05
rmse: 0.0060047679936635935
mape: 0.014133968610125974
rsquared: 0.9965476836013605
<DatetimeArray>
['2003-01-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1208
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 4.222314064147399e-05
rmse: 0.006497933567025289
mape: 0.014576105437956954
rsquared: 0.9948674169344165
<DatetimeArray>
['2003-01-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1286
Run 001 | Training Loss: 0.0006
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 7.57830876206509e-05
rmse: 0.008705348219379332
mape: 0.019430375138703986
rsquared: 0.9939403753455094
<DatetimeArray>
['2003-01-08 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1575
Run 001 | Training Loss: 0.0008
Run 002 | Training Loss: 0.0003
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 7.582110392453055e-05
rmse: 0.008707531448380221
mape: 0.019953724314258514
rsquared: 0.9923057088088049
<DatetimeArray>
['2003-01-09 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1833
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 6.373795537339925e-05
rmse: 0.00798360541193008
mape: 0.014537744162344067
rsquared: 0.9927142210459493
<DatetimeArray>
['2003-01-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1348
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 6.396914602340258e-05
rmse: 0.007998071393992591
mape: 0.01569062933286319
rsquared: 0.9961459422604481
<DatetimeArray>
['2003-01-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1421
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.56697029060636e-05
rmse: 0.005972411816516306
mape: 0.012273824971511433
rsquared: 0.9958764801952855
<DatetimeArray>
['2003-01-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1694
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 1.6413359390724575e-05
rmse: 0.004051340443695713
mape: 0.010105025978199253
rsquared: 0.9982910391970765
<DatetimeArray>
['2003-01-15 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1264
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 7.534982503540673e-05
rmse: 0.008680427698875599
mape: 0.014727754235534523
rsquared: 0.9933900707247292
<DatetimeArray>
['2003-01-16 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1807
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 2.657232457380889e-05
rmse: 0.00515483506756607
mape: 0.010421075371562758
rsquared: 0.997893158001067
<DatetimeArray>
['2003-01-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1641
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.698259251042153e-05
rmse: 0.006081331475131209
mape: 0.012708012703836981
rsquared: 0.9964259958194465
<DatetimeArray>
['2003-01-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1278
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 7.73045637831236e-05
rmse: 0.008792301392873405
mape: 0.014668127445157246
rsquared: 0.9904826985276886
<DatetimeArray>
['2003-01-22 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1261
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 5.0404337088743854e-05
rmse: 0.007099601192232128
mape: 0.014047202756087902
rsquared: 0.9922858552229561
<DatetimeArray>
['2003-01-23 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1470
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.163846358465345e-05
rmse: 0.00562480787091021
mape: 0.011988535274064233
rsquared: 0.9966515790152249
<DatetimeArray>
['2003-01-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1190
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00022319768431547647
rmse: 0.014939802017278424
mape: 0.012357393146457132
rsquared: 0.9777603117114784
<DatetimeArray>
['2003-01-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1035
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00010551468642025654
rmse: 0.010272034190960257
mape: 0.012612717678053881
rsquared: 0.9905176700443056
<DatetimeArray>
['2003-01-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1138
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 5.9071106953997936e-05
rmse: 0.007685773022539628
mape: 0.01181581409365382
rsquared: 0.995184238898462
<DatetimeArray>
['2003-01-29 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1698
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.0279486469272206e-05
rmse: 0.005502679935201774
mape: 0.011037971239659541
rsquared: 0.9954347978783729
<DatetimeArray>
['2003-01-30 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1038
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.0102507635526128e-05
rmse: 0.005486575219162326
mape: 0.009831729070841474
rsquared: 0.9965909356127278
<DatetimeArray>
['2003-01-31 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1177
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.999497266571464e-05
rmse: 0.0063241578621753775
mape: 0.010486290060581712
rsquared: 0.9955905562185564
<DatetimeArray>
['2003-02-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1376
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.8973247861197395e-05
rmse: 0.006242855745666192
mape: 0.011285380627789167
rsquared: 0.995331445699533
<DatetimeArray>
['2003-02-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1550
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.828523229756008e-05
rmse: 0.006187506145254328
mape: 0.01061859525838441
rsquared: 0.994908260622856
<DatetimeArray>
['2003-02-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1522
Run 001 | Training Loss: 0.0005
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 0.00010494178600937556
rmse: 0.010244109820251614
mape: 0.01395481805906726
rsquared: 0.9870882176756847
<DatetimeArray>
['2003-02-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1055
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.95134348625509e-05
rmse: 0.0062859712743975294
mape: 0.011727518457936981
rsquared: 0.9959269621572405
<DatetimeArray>
['2003-02-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1142
Run 001 | Training Loss: 0.0005
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 9.384578877737591e-05
rmse: 0.009687403613836677
mape: 0.013240711679528871
rsquared: 0.9883387491525019
<DatetimeArray>
['2003-02-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1639
Run 001 | Training Loss: 0.0005
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 0.00015436993090154016
rmse: 0.012424569646532638
mape: 0.014750368967285293
rsquared: 0.9845540898046605
<DatetimeArray>
['2003-02-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1400
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 7.896886825062046e-05
rmse: 0.008886442947018815
mape: 0.013629038673619993
rsquared: 0.9890342542986688
<DatetimeArray>
['2003-02-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1269
Run 001 | Training Loss: 0.0006
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 7.005132255746188e-05
rmse: 0.008369666812810525
mape: 0.011888190818289781
rsquared: 0.9962475604735892
<DatetimeArray>
['2003-02-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1219
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.0001259913435484581
rmse: 0.011224586564700639
mape: 0.018062358845062205
rsquared: 0.99310638743725
<DatetimeArray>
['2003-02-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1122
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.000746715178684712
rmse: 0.0273260897071775
mape: 0.015759652355279184
rsquared: 0.9798906449274076
<DatetimeArray>
['2003-02-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1574
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 2.945124457877415e-05
rmse: 0.005426900089256679
mape: 0.013047009468043765
rsquared: 0.9962055332256744
<DatetimeArray>
['2003-02-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1415
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 1.997312079126625e-05
rmse: 0.004469129757711925
mape: 0.010109167852706498
rsquared: 0.9981296058634477
<DatetimeArray>
['2003-02-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1484
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.940441637016249e-05
rmse: 0.0062772937138676635
mape: 0.011698153450476582
rsquared: 0.9963056272839635
<DatetimeArray>
['2003-02-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1307
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 3.5143421076269954e-05
rmse: 0.005928188684266886
mape: 0.013614703405270075
rsquared: 0.9976219079083413
<DatetimeArray>
['2003-02-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1116
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 8.762033973862065e-05
rmse: 0.009360573686405159
mape: 0.015121728093278844
rsquared: 0.9876648341027358
<DatetimeArray>
['2003-02-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1067
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 6.128770076308867e-05
rmse: 0.00782864616412625
mape: 0.014611733668906208
rsquared: 0.9948026514686706
<DatetimeArray>
['2003-02-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1225
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.0007877962919075337
rmse: 0.028067709060547383
mape: 0.01616289565429839
rsquared: 0.9147608931870603
<DatetimeArray>
['2003-02-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1613
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.700714303791126e-05
rmse: 0.006856175540190848
mape: 0.01282884459088674
rsquared: 0.993794332513443
<DatetimeArray>
['2003-02-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1659
Run 001 | Training Loss: 0.0005
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 5.784558227883335e-05
rmse: 0.007605628328996451
mape: 0.017006186908303564
rsquared: 0.993889511689447
<DatetimeArray>
['2003-03-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1130
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.930852531972199e-05
rmse: 0.007022002942161302
mape: 0.012072104813836216
rsquared: 0.9942575943214377
<DatetimeArray>
['2003-03-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1140
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 5.246720761288096e-05
rmse: 0.0072434251299285865
mape: 0.015147652449778844
rsquared: 0.9931164387946604
<DatetimeArray>
['2003-03-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1591
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 6.295200354952332e-05
rmse: 0.0079342298649285
mape: 0.016907600324877772
rsquared: 0.9972474253065793
<DatetimeArray>
['2003-03-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1422
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 4.9729720688131525e-05
rmse: 0.0070519302810033175
mape: 0.013612109575963295
rsquared: 0.9933189839162393
<DatetimeArray>
['2003-03-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1774
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 5.888258165817546e-05
rmse: 0.007673498658250711
mape: 0.014471321415266844
rsquared: 0.994531935758177
<DatetimeArray>
['2003-03-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1007
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.0001475080863445437
rmse: 0.012145290706464943
mape: 0.01902885536208892
rsquared: 0.9878960728177104
<DatetimeArray>
['2003-03-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1262
Run 001 | Training Loss: 0.0011
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00013270874949936426
rmse: 0.011519928363464951
mape: 0.016920049784340602
rsquared: 0.9969364558939453
<DatetimeArray>
['2003-03-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1137
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.0015039159620128181
rmse: 0.03878035536212656
mape: 0.017169024377487692
rsquared: 0.9430069831954873
<DatetimeArray>
['2003-03-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1396
Run 001 | Training Loss: 0.0007
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.0001703436727202367
rmse: 0.013051577403526238
mape: 0.01706752967689718
rsquared: 0.9912133490608386
<DatetimeArray>
['2003-03-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1213
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00017401831756778662
rmse: 0.013191600265615487
mape: 0.020163931704009104
rsquared: 0.995932617957463
<DatetimeArray>
['2003-03-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1376
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.148584970406947e-05
rmse: 0.006440950993764001
mape: 0.013407621590743355
rsquared: 0.9925621307654772
<DatetimeArray>
['2003-03-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1092
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.124645674492577e-05
rmse: 0.00558985301639728
mape: 0.011503525263864984
rsquared: 0.9969933871562345
<DatetimeArray>
['2003-03-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1186
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00014732805756878604
rmse: 0.012137876979471576
mape: 0.014265262645264145
rsquared: 0.976127830418847
<DatetimeArray>
['2003-03-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1265
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00015554343069443916
rmse: 0.012471705203958244
mape: 0.012439004810376457
rsquared: 0.9791689904310181
<DatetimeArray>
['2003-03-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1186
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 2.1789008768108514e-05
rmse: 0.004667869831958525
mape: 0.009451835780292697
rsquared: 0.9962509871841805
<DatetimeArray>
['2003-03-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1739
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.718949365109935e-05
rmse: 0.006098318920087678
mape: 0.010421792836033623
rsquared: 0.9945983116615845
<DatetimeArray>
['2003-03-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1204
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 5.126427537301529e-05
rmse: 0.007159907497518057
mape: 0.010134144211193154
rsquared: 0.9910288375543211
<DatetimeArray>
['2003-03-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1485
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.206456855904306e-05
rmse: 0.00566255848173271
mape: 0.010711589492210316
rsquared: 0.995498099443768
<DatetimeArray>
['2003-03-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1850
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,ddelta,dgamma,...,stock_price,realized_vol,moneyness,impl_volatility,impl_vol_ann,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2003-01-02,2003-02-22,C,90.0,1.30,1.50,1464.0,5083.0,0.309251,0.047734,...,86.08,0.030519,0.044533,0.233642,0.233130,0,0.000087,0.009347,0.018246,0.991530
1,2003-01-02,2003-02-22,C,91.0,0.95,1.15,255.0,540.0,0.256302,0.045347,...,86.08,0.030519,0.055582,0.224751,0.228661,1,0.000087,0.009347,0.018246,0.991530
2,2003-01-02,2003-02-22,C,92.0,0.75,0.95,0.0,355.0,0.216934,0.041150,...,86.08,0.030519,0.066511,0.225981,0.224484,1,0.000087,0.009347,0.018246,0.991530
3,2003-01-02,2003-02-22,C,94.0,0.40,0.55,0.0,835.0,0.139982,0.032262,...,86.08,0.030519,0.088018,0.218488,0.217118,0,0.000087,0.009347,0.018246,0.991530
4,2003-01-02,2003-03-22,C,90.0,2.15,2.45,2028.0,13151.0,0.361403,0.037649,...,86.08,0.048298,0.044533,0.250788,0.250963,0,0.000087,0.009347,0.018246,0.991530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163837,2003-12-31,2004-09-18,P,975.0,20.10,22.10,0.0,744.0,-0.191240,0.001474,...,1111.92,0.093558,-0.131406,0.196156,0.196785,1,0.000016,0.004056,0.010601,0.994763
163838,2003-12-31,2004-09-18,P,995.0,23.50,25.50,607.0,4679.0,-0.220435,0.001657,...,1111.92,0.093558,-0.111101,0.189753,0.190702,0,0.000016,0.004056,0.010601,0.994763
163839,2003-12-31,2004-09-18,P,900.0,11.50,13.10,3150.0,4822.0,-0.111764,0.000908,...,1111.92,0.093558,-0.211449,0.222397,0.221433,1,0.000016,0.004056,0.010601,0.994763
163840,2003-12-31,2004-03-20,P,1500.0,387.50,389.50,0.0,13601.0,-0.986928,0.000187,...,1111.92,0.023402,0.299377,0.270825,0.298932,1,0.000016,0.004056,0.010601,0.994763
163841,2003-12-31,2004-06-19,P,1500.0,387.20,389.20,0.0,326.0,-0.979654,0.000230,...,1111.92,0.059106,0.299377,0.193454,0.195079,1,0.000016,0.004056,0.010601,0.994763

In [10]:
##### ANN torch calibration and estimation function with code data pipeline correction:
def ANN_function_torch_LBFGS_variable(data, x_cols, y_cols, ignore, model, criterion, optimizer, batch = 2048, log_y = False, params=None):

    X, Y = data[x_cols].copy(), data[y_cols].copy()
    
    label_encoders_ivol = {}
    categorical_columns = []
    for col in categorical_columns:
        label_encoder = LabelEncoder()
        X[col] = label_encoder.fit_transform(X[col])
        label_encoders_ivol[col] = label_encoder

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size= 0.7, shuffle = True, random_state = 0)


    scaler_X_ivol = StandardScaler()

    non_categ_cols_ivol = [col for col in X_train.columns if col not in ignore]
    X_train_encoded_ivol_std = X_train.copy()
    X_test_encoded_ivol_std = X_test.copy()
    X_train_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.fit_transform(X_train_encoded_ivol_std[non_categ_cols_ivol])
    X_test_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.transform(X_test_encoded_ivol_std[non_categ_cols_ivol])

    if log_y:
        Y_train_ivol_std = np.log(Y_train)
        Y_test_ivol_std  = np.log(Y_test)
    else:
        Y_train_ivol_std = Y_train
        Y_test_ivol_std  = Y_test




    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")




    model.train()
    n = len(X_train_encoded_ivol_std)


    for i in range(0, n, batch):
        end = min(i + batch, n)
        xb = torch.as_tensor(X_train_encoded_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)
        yb = torch.as_tensor(Y_train_ivol_std.iloc[i:end].values, device=device, dtype=torch.float32)

        def closure():
            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()
            return loss

        for ii in range(5):
            total_loss = 0
            loss_temp = optimizer.step(closure)

            total_loss += loss_temp



            print(f"Run {ii:03d} | Training Loss: {total_loss:.4f}")
    

    model.eval()
    with torch.no_grad():
        
        X_test_encoded_ivol_std_t = torch.from_numpy(X_test_encoded_ivol_std.values.astype(np.float32)).to(device)
        X_train_encoded_ivol_std_t = torch.from_numpy(X_train_encoded_ivol_std.values.astype(np.float32)).to(device)
        y_pred_ann_ivol = model(X_test_encoded_ivol_std_t).cpu().numpy()
        y_pred_ann_ivol_train = model(X_train_encoded_ivol_std_t).cpu().numpy()

    if log_y:
        y_pred_ann_ivol       = np.exp(y_pred_ann_ivol)
        y_pred_ann_ivol_train = np.exp(y_pred_ann_ivol_train)

    rmse_ann_ivol = np.sqrt(mean_squared_error(Y_test.values.ravel(), y_pred_ann_ivol))
    mse_ann_ivol = mean_squared_error(Y_test.values.ravel(), y_pred_ann_ivol)
    mape_ann_ivol = mean_absolute_percentage_error(Y_test.values.ravel(), y_pred_ann_ivol)
    rsquared_ann_ivol = r2_score(Y_test.values.ravel(), y_pred_ann_ivol)


    print("mse:", mse_ann_ivol)
    print("rmse:", rmse_ann_ivol)
    print("mape:", mape_ann_ivol)
    print("rsquared:", rsquared_ann_ivol)


    for col in categorical_columns:
        X_test_encoded_ivol_std[col] = label_encoders_ivol[col].inverse_transform(X_test_encoded_ivol_std[col])
        X_train_encoded_ivol_std[col] = label_encoders_ivol[col].inverse_transform(X_train_encoded_ivol_std[col])

    X_test_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_test_encoded_ivol_std[non_categ_cols_ivol])
    X_train_encoded_ivol_std[non_categ_cols_ivol] = scaler_X_ivol.inverse_transform(X_train_encoded_ivol_std[non_categ_cols_ivol])

    if log_y:
        Y_test_ivol_std  = np.exp(Y_test_ivol_std)
        Y_train_ivol_std = np.exp(Y_train_ivol_std)

    output_ann_ivol = pd.concat([X_test_encoded_ivol_std, 
                                 Y_test_ivol_std.set_axis(X_test_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol, columns = ["output_ann"]).set_axis(X_test_encoded_ivol_std.index)], axis=1)
    output_ann_ivol_train = pd.concat([X_train_encoded_ivol_std, 
                                 Y_train_ivol_std.set_axis(X_train_encoded_ivol_std.index), 
                                 pd.DataFrame(y_pred_ann_ivol_train, columns = ["output_ann"]).set_axis(X_train_encoded_ivol_std.index)], axis=1)


    output_ann_ivol["out_of_sample"] = 1
    output_ann_ivol_train["out_of_sample"] = 0

    output_ann_ivol_full = pd.concat([output_ann_ivol_train, output_ann_ivol], axis = 0)

    data_clean = data.drop(columns = [col for col in data.columns if col in output_ann_ivol_full.columns])
    data_out = pd.concat([data_clean, output_ann_ivol_full], axis = 1)

    data_out["mse_optim"] = mse_ann_ivol
    data_out["rmse_optim"] = rmse_ann_ivol
    data_out["mape_optim"] = mape_ann_ivol
    data_out["rsquared_optim"] = rsquared_ann_ivol

    return(data_out)

In [16]:
# ANN variable LBGFS loop:
set_seed(42)

_p        = params_lbfgs_variable_ivol
_n_units  = _p.get('n_units',     64)
_n_layers = _p.get('n_layers',    3)
_max_iter = _p.get('max_iter',    20)
_hist_sz  = _p.get('history_size', 1)
device    = torch.device("cuda")


grouped_data = data.groupby(['date'])
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['impl_volatility']
ignore = ["cp_flag_one"]


_lrs = [nn.Linear(len(selected_columns_x), _n_units), nn.GELU()]
for _ in range(_n_layers - 1):
    _lrs += [nn.Linear(_n_units, _n_units), nn.GELU()]
_lrs.append(nn.Linear(_n_units, 1))
model = nn.Sequential(*_lrs).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.LBFGS(
    model.parameters(),
    max_iter=_max_iter,
    history_size=_hist_sz,
    line_search_fn="strong_wolfe"
)


results = {}

for i, group in grouped_data:
    print(group["date"].unique())
    
    temp = ANN_function_torch_LBFGS_variable(group, selected_columns_x, selected_columns_y, ignore, model=model, criterion=criterion, optimizer=optimizer)
    results[i] = temp.copy()
    del temp, group
    torch.cuda.synchronize()
    torch.cuda.empty_cache()



variable_ann_lbfgs_ivol_data = pd.concat(results.values())
variable_ann_lbfgs_ivol_data

_oos = variable_ann_lbfgs_ivol_data[variable_ann_lbfgs_ivol_data["out_of_sample"] == 1]
print("mse:", mean_squared_error(_oos["impl_volatility"], _oos["output_ann"]))
print("rmse:", np.sqrt(mean_squared_error(_oos["impl_volatility"], _oos["output_ann"])))
print("mape:", mean_absolute_percentage_error(_oos["impl_volatility"], _oos["output_ann"]))
print("rsquared:", r2_score(_oos["impl_volatility"], _oos["output_ann"]))

variable_ann_lbfgs_ivol_data = variable_ann_lbfgs_ivol_data.rename(columns={"output_ann":"impl_vol_ann"})
variable_ann_lbfgs_ivol_data

<DatetimeArray>
['2003-01-02 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1849
Run 001 | Training Loss: 0.0027
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0003
Run 004 | Training Loss: 0.0002
mse: 0.0002307290066710268
rmse: 0.015189766511405854
mape: 0.033008882621907376
rsquared: 0.9776279020482082
<DatetimeArray>
['2003-01-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0037
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 7.614917847103812e-05
rmse: 0.008726349664724542
mape: 0.02257897026111183
rsquared: 0.9927090629408982
<DatetimeArray>
['2003-01-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0071
Run 001 | Training Loss: 0.0006
Run 002 | Training Loss: 0.0003
Run 003 | Training Loss: 0.0002
Run 004 | Training Loss: 0.0002
mse: 0.00023235991570601274
rmse: 0.015243356444891418
mape: 0.03323664934589461
rsquared: 0.9717546693506344
<DatetimeArray>
['2003-01-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0073
Run 001 | Training Loss: 0.0007
Run 002 | Training Loss: 0.0005
Run 003 | Training Loss: 0.0004
Run 004 | Training Loss: 0.0004
mse: 0.00023002225142793547
rmse: 0.015166484478214965
mape: 0.0321329498806382
rsquared: 0.9816073935544646
<DatetimeArray>
['2003-01-08 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0009
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0004
Run 003 | Training Loss: 0.0003
Run 004 | Training Loss: 0.0003
mse: 0.00019169416436563038
rmse: 0.013845366169431215
mape: 0.031017245366278094
rsquared: 0.9805469632603859
<DatetimeArray>
['2003-01-09 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0091
Run 001 | Training Loss: 0.0006
Run 002 | Training Loss: 0.0003
Run 003 | Training Loss: 0.0002
Run 004 | Training Loss: 0.0002
mse: 0.0002269254862917636
rmse: 0.015064046146097788
mape: 0.02926721073005059
rsquared: 0.9740605276326098
<DatetimeArray>
['2003-01-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0046
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.0001586201587703283
rmse: 0.012594449522322453
mape: 0.02460222210945564
rsquared: 0.9904433420084412
<DatetimeArray>
['2003-01-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0061
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 0.00012088777310174889
rmse: 0.010994897593963706
mape: 0.018247877362146146
rsquared: 0.9860250272382238
<DatetimeArray>
['2003-01-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0034
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 4.427740696255506e-05
rmse: 0.0066541270623993246
mape: 0.017054313434557742
rsquared: 0.9953898314688181
<DatetimeArray>
['2003-01-15 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0027
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00018873353118736437
rmse: 0.01373803228950072
mape: 0.023675140733508016
rsquared: 0.9834436869304689
<DatetimeArray>
['2003-01-16 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0004
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.792785708749463e-05
rmse: 0.0069229948062594
mape: 0.013547349122998395
rsquared: 0.9961999402065742
<DatetimeArray>
['2003-01-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0004
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 5.38705146000939e-05
rmse: 0.007339653574937573
mape: 0.014425312768913387
rsquared: 0.9947939440877474
<DatetimeArray>
['2003-01-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0005
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 5.4960418506721224e-05
rmse: 0.007413529423069772
mape: 0.016841082858825577
rsquared: 0.9932335835508969
<DatetimeArray>
['2003-01-22 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0007
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 5.904330904521959e-05
rmse: 0.007683964409419111
mape: 0.01710692524109576
rsquared: 0.990963701530512
<DatetimeArray>
['2003-01-23 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0029
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 6.160999268983138e-05
rmse: 0.00784920331561308
mape: 0.01849165460993491
rsquared: 0.9934795761544332
<DatetimeArray>
['2003-01-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0035
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00014242214256878887
rmse: 0.011934074851817751
mape: 0.013882925649049322
rsquared: 0.9858088847748246
<DatetimeArray>
['2003-01-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0006
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00010227088684744832
rmse: 0.010112906943478137
mape: 0.01215960488608688
rsquared: 0.9908091818603668
<DatetimeArray>
['2003-01-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0076
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 5.946311502269566e-05
rmse: 0.0077112330416539525
mape: 0.01311389561898257
rsquared: 0.9951522805129488
<DatetimeArray>
['2003-01-29 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0042
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 4.8921124328389504e-05
rmse: 0.006994363754366047
mape: 0.012885780464499468
rsquared: 0.9926242203346813
<DatetimeArray>
['2003-01-30 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0005
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 2.7951957514782487e-05
rmse: 0.005286961085045216
mape: 0.009973043314936293
rsquared: 0.996834482227463
<DatetimeArray>
['2003-01-31 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0002
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 8.133548142554357e-05
rmse: 0.009018618598518487
mape: 0.0109609369684027
rsquared: 0.9910327671485064
<DatetimeArray>
['2003-02-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0003
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 5.335706324237426e-05
rmse: 0.00730459192853196
mape: 0.011664400894988854
rsquared: 0.9936084272999869
<DatetimeArray>
['2003-02-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0054
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 4.9530985332873726e-05
rmse: 0.007037825326965264
mape: 0.014778513932571919
rsquared: 0.9934126331937077
<DatetimeArray>
['2003-02-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0013
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 9.875168585515215e-05
rmse: 0.009937388281392257
mape: 0.013653439385431832
rsquared: 0.9878498325556706
<DatetimeArray>
['2003-02-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0020
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 6.226539612388993e-05
rmse: 0.00789084254841585
mape: 0.011973643876918641
rsquared: 0.9935816940342138
<DatetimeArray>
['2003-02-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0013
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00019175427514401186
rmse: 0.013847536789769214
mape: 0.016858059089504704
rsquared: 0.976172668665623
<DatetimeArray>
['2003-02-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0023
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00022071472337876558
rmse: 0.014856470757847086
mape: 0.016305843204142398
rsquared: 0.9779157781817496
<DatetimeArray>
['2003-02-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0007
Run 001 | Training Loss: 0.0000
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 6.978905546729854e-05
rmse: 0.00835398440669472
mape: 0.012944763534037647
rsquared: 0.9903089780575083
<DatetimeArray>
['2003-02-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0078
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00011083082032953007
rmse: 0.010527621779373064
mape: 0.016451511675400328
rsquared: 0.9940631249237597
<DatetimeArray>
['2003-02-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0164
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00015648902878960156
rmse: 0.01250955749775353
mape: 0.020475497720613068
rsquared: 0.9914377075089954
<DatetimeArray>
['2003-02-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0011
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 0.00025791173819946693
rmse: 0.016059630699348817
mape: 0.019996939016012728
rsquared: 0.9930543279835584
<DatetimeArray>
['2003-02-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0017
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.508485773151173e-05
rmse: 0.005923247228633272
mape: 0.01417454340851486
rsquared: 0.9954797045473551
<DatetimeArray>
['2003-02-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0004
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 1.928057247880129e-05
rmse: 0.004390964868773296
mape: 0.009630823791369118
rsquared: 0.9981944599399063
<DatetimeArray>
['2003-02-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0001
Run 001 | Training Loss: 0.0000
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.553384296803627e-05
rmse: 0.005961027006148879
mape: 0.009575672105121728
rsquared: 0.996668514038532
<DatetimeArray>
['2003-02-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0155
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 7.713705530197595e-05
rmse: 0.00878277036600502
mape: 0.01749075051002605
rsquared: 0.9947802742143582
<DatetimeArray>
['2003-02-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0010
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00010320349682989653
rmse: 0.010158912187330714
mape: 0.01810754531781923
rsquared: 0.985471041788104
<DatetimeArray>
['2003-02-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0007
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.434902721375469e-05
rmse: 0.005860804314576174
mape: 0.01206655323585813
rsquared: 0.9970871175795598
<DatetimeArray>
['2003-02-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0016
Run 001 | Training Loss: 0.0000
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.444219934018378e-05
rmse: 0.006666498281720605
mape: 0.012089928944041655
rsquared: 0.9951913795285996
<DatetimeArray>
['2003-02-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0027
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.400187740707346e-05
rmse: 0.00663339109408404
mape: 0.012513811845187753
rsquared: 0.9941910739022722
<DatetimeArray>
['2003-02-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0013
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 4.176437963190903e-05
rmse: 0.006462536625188984
mape: 0.014887544541737716
rsquared: 0.9955882412539624
<DatetimeArray>
['2003-03-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0004
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 5.984774420895989e-05
rmse: 0.007736132380521929
mape: 0.012759783294797529
rsquared: 0.9930302108212266
<DatetimeArray>
['2003-03-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0005
Run 001 | Training Loss: 0.0000
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.676798233173981e-05
rmse: 0.006063660802826937
mape: 0.013790720224597515
rsquared: 0.9951761363279558
<DatetimeArray>
['2003-03-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0097
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 7.433120849312167e-05
rmse: 0.008621554876767976
mape: 0.01715152933544965
rsquared: 0.9967498698708043
<DatetimeArray>
['2003-03-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0052
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 4.398590598005783e-05
rmse: 0.006632187118896588
mape: 0.014162215311267533
rsquared: 0.9940906455687838
<DatetimeArray>
['2003-03-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0038
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 7.698649035697899e-05
rmse: 0.008774194570271336
mape: 0.015497267746270886
rsquared: 0.9928507367854854
<DatetimeArray>
['2003-03-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0022
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 7.711160409087285e-05
rmse: 0.008781321318051906
mape: 0.015202533529754408
rsquared: 0.9936725283070558
<DatetimeArray>
['2003-03-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0048
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0002
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 9.659076238979406e-05
rmse: 0.009828059950457876
mape: 0.01866532807201108
rsquared: 0.9977702294540873
<DatetimeArray>
['2003-03-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0123
Run 001 | Training Loss: 0.0003
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00031065647385996497
rmse: 0.017625449607313992
mape: 0.018361273200756447
rsquared: 0.9882272347110173
<DatetimeArray>
['2003-03-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0013
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0000
mse: 0.00013062797382840832
rmse: 0.011429259548562554
mape: 0.014310083765919777
rsquared: 0.993261960420419
<DatetimeArray>
['2003-03-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0035
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 0.00011367094200468103
rmse: 0.010661657563656836
mape: 0.01718205608602258
rsquared: 0.9973431351668597
<DatetimeArray>
['2003-03-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0033
Run 001 | Training Loss: 0.0002
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0001
Run 004 | Training Loss: 0.0001
mse: 3.388484211595949e-05
rmse: 0.005821068812164952
mape: 0.013305356580876195
rsquared: 0.9939248918248326
<DatetimeArray>
['2003-03-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0023
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.252700209061307e-05
rmse: 0.005703244873807635
mape: 0.011989206349517782
rsquared: 0.9968701698546762
<DatetimeArray>
['2003-03-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0006
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00011741167621091519
rmse: 0.010835666855847645
mape: 0.014636985517951371
rsquared: 0.9809753044222024
<DatetimeArray>
['2003-03-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0002
Run 001 | Training Loss: 0.0000
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 0.00012445704243289709
rmse: 0.011156031661522707
mape: 0.012529492769768754
rsquared: 0.9833322061222894
<DatetimeArray>
['2003-03-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0010
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.163907531368314e-05
rmse: 0.005624862248418457
mape: 0.012327812228050027
rsquared: 0.9945561865574496
<DatetimeArray>
['2003-03-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0036
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.9049899498175487e-05
rmse: 0.00624899187854933
mape: 0.011393424756308116
rsquared: 0.9943280919951607
<DatetimeArray>
['2003-03-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0020
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0001
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 6.998376243275443e-05
rmse: 0.00836562982881471
mape: 0.012097332930154194
rsquared: 0.9877529586290705
<DatetimeArray>
['2003-03-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0011
Run 001 | Training Loss: 0.0001
Run 002 | Training Loss: 0.0000
Run 003 | Training Loss: 0.0000
Run 004 | Training Loss: 0.0000
mse: 3.367325336060763e-05
rmse: 0.005802865960937546
mape: 0.012120476708846849
rsquared: 0.9952722383351231
<DatetimeArray>
['2003-03-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0005

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,ddelta,dgamma,...,stock_price,realized_vol,moneyness,impl_volatility,impl_vol_ann,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2003-01-02,2003-02-22,C,90.0,1.30,1.50,1464.0,5083.0,0.309251,0.047734,...,86.08,0.030519,0.044533,0.233642,0.230486,0,0.000231,0.015190,0.033009,0.977628
1,2003-01-02,2003-02-22,C,91.0,0.95,1.15,255.0,540.0,0.256302,0.045347,...,86.08,0.030519,0.055582,0.224751,0.225330,1,0.000231,0.015190,0.033009,0.977628
2,2003-01-02,2003-02-22,C,92.0,0.75,0.95,0.0,355.0,0.216934,0.041150,...,86.08,0.030519,0.066511,0.225981,0.220404,1,0.000231,0.015190,0.033009,0.977628
3,2003-01-02,2003-02-22,C,94.0,0.40,0.55,0.0,835.0,0.139982,0.032262,...,86.08,0.030519,0.088018,0.218488,0.211213,0,0.000231,0.015190,0.033009,0.977628
4,2003-01-02,2003-03-22,C,90.0,2.15,2.45,2028.0,13151.0,0.361403,0.037649,...,86.08,0.048298,0.044533,0.250788,0.249270,0,0.000231,0.015190,0.033009,0.977628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163837,2003-12-31,2004-09-18,P,975.0,20.10,22.10,0.0,744.0,-0.191240,0.001474,...,1111.92,0.093558,-0.131406,0.196156,0.198107,1,0.000032,0.005684,0.016780,0.989715
163838,2003-12-31,2004-09-18,P,995.0,23.50,25.50,607.0,4679.0,-0.220435,0.001657,...,1111.92,0.093558,-0.111101,0.189753,0.192332,0,0.000032,0.005684,0.016780,0.989715
163839,2003-12-31,2004-09-18,P,900.0,11.50,13.10,3150.0,4822.0,-0.111764,0.000908,...,1111.92,0.093558,-0.211449,0.222397,0.220180,1,0.000032,0.005684,0.016780,0.989715
163840,2003-12-31,2004-03-20,P,1500.0,387.50,389.50,0.0,13601.0,-0.986928,0.000187,...,1111.92,0.023402,0.299377,0.270825,0.223693,1,0.000032,0.005684,0.016780,0.989715
163841,2003-12-31,2004-06-19,P,1500.0,387.20,389.20,0.0,326.0,-0.979654,0.000230,...,1111.92,0.059106,0.299377,0.193454,0.183647,1,0.000032,0.005684,0.016780,0.989715

Surface Estimation through Option Price modelling

In [3]:
# GPU Implied Vol estimator (Newton Rhapson method) with batching and parallelization

def bs_price_torch(S, K, T, r, cp, sigma):
    eps = 1e-12
    sigma = torch.clamp(sigma, min=eps)
    T = torch.clamp(T, min=eps)

    d1 = (torch.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * torch.sqrt(T))
    d2 = d1 - sigma * torch.sqrt(T)

    normal = torch.distributions.Normal(0.0, 1.0)
    return cp * (S * normal.cdf(cp * d1) - K * torch.exp(-r * T) * normal.cdf(cp * d2))

def bs_vega_torch(S, K, T, r, sigma):
    eps = 1e-12
    sigma = torch.clamp(sigma, min=eps)
    T = torch.clamp(T, min=eps)

    d1 = (torch.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * torch.sqrt(T))
    normal = torch.distributions.Normal(0.0, 1.0)
    return S * normal.log_prob(d1).exp() * torch.sqrt(T)


def implied_vol_newton_gpu_batched(
    dfs: list[pd.DataFrame],
    price_cols: list[str],
    batch_size: int = 10_000,
    initial_guess: float = 0.2,
    tol: float = 1e-10,
    max_iter: int = 100,
) -> list[torch.Tensor]:
    """
    Compute implied vol for N dataframes in a single batched GPU pass,
    processing `batch_size` rows at a time to respect GPU memory limits.

    Parameters
    ----------
    dfs        : list of DataFrames, all sharing the same index/length
    price_cols : price column name per DataFrame (same order as dfs)
    batch_size : number of rows per GPU batch (tune to VRAM budget)

    Returns
    -------
    List of 1-D tensors (one per DataFrame) with implied vols, on CPU.
    """
    dtype  = torch.float64
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    n      = len(dfs[0])
    N      = len(dfs)

    S_np     = [df["stock_price"].values  for df in dfs]
    K_np     = [df["strike_price"].values for df in dfs]
    T_np     = [df["time_to_mat"].values  for df in dfs]
    r_np     = [df["rf"].values           for df in dfs]
    cp_np    = [df["cp_flag_one"].values  for df in dfs]
    price_np = [df[col].values for df, col in zip(dfs, price_cols)]

    results = [torch.empty(n, dtype=dtype) for _ in range(N)]

    for batch_start in range(0, n, batch_size):
        batch_end = min(batch_start + batch_size, n)
        sl = slice(batch_start, batch_end)

        def to_gpu(arr):
            return torch.as_tensor(arr[sl], dtype=dtype, device=device)

        S  = torch.stack([to_gpu(s)  for s  in S_np],  dim=0)
        K  = torch.stack([to_gpu(k)  for k  in K_np],  dim=0)
        T  = torch.stack([to_gpu(t)  for t  in T_np],  dim=0)
        r  = torch.stack([to_gpu(rv) for rv in r_np],  dim=0)
        cp = torch.stack([to_gpu(c)  for c  in cp_np], dim=0)

        prices = torch.stack(
            [torch.as_tensor(p[sl], dtype=dtype, device=device) for p in price_np],
            dim=0,
        )

        sigma = torch.full((N, batch_end - batch_start), initial_guess,
                           dtype=dtype, device=device)

        for _ in range(max_iter):
            price_est = bs_price_torch(S, K, T, r, cp, sigma)
            vega      = bs_vega_torch(S, K, T, r, sigma)

            diff      = price_est - prices
            converged = torch.abs(diff) < tol

            if torch.all(converged):
                break

            vega  = torch.clamp(vega, min=1e-12)
            sigma = sigma - diff / vega
            sigma = torch.clamp(sigma, min=1e-8, max=5.0)

        for i in range(N):
            results[i][sl] = sigma[i].cpu()

        del S, K, T, r, cp, prices, sigma, price_est, vega, diff, converged
        torch.cuda.empty_cache()

    return results


def bs_price_from_iv_gpu_batched(
    dfs: list[pd.DataFrame],
    iv_cols: list[str],
    batch_size: int = 10_000,
) -> list[torch.Tensor]:
    """
    Compute Black-Scholes prices from implied volatilities for N dataframes,
    processing `batch_size` rows at a time.

    Parameters
    ----------
    dfs     : list of DataFrames sharing the same index/length
    iv_cols : IV column name per DataFrame (same order as dfs)

    Returns
    -------
    List of 1-D tensors (one per DataFrame) with BS prices, on CPU.
    """
    dtype  = torch.float64
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    n      = len(dfs[0])
    N      = len(dfs)

    S_np  = [df["stock_price"].values  for df in dfs]
    K_np  = [df["strike_price"].values for df in dfs]
    T_np  = [df["time_to_mat"].values  for df in dfs]
    r_np  = [df["rf"].values           for df in dfs]
    cp_np = [df["cp_flag_one"].values  for df in dfs]
    iv_np = [df[col].values for df, col in zip(dfs, iv_cols)]

    results = [torch.empty(n, dtype=dtype) for _ in range(N)]

    for batch_start in range(0, n, batch_size):
        batch_end = min(batch_start + batch_size, n)
        sl = slice(batch_start, batch_end)

        def to_gpu(arr):
            return torch.as_tensor(arr[sl], dtype=dtype, device=device)

        S  = torch.stack([to_gpu(s)  for s  in S_np],  dim=0)
        K  = torch.stack([to_gpu(k)  for k  in K_np],  dim=0)
        T  = torch.stack([to_gpu(t)  for t  in T_np],  dim=0)
        r  = torch.stack([to_gpu(rv) for rv in r_np],  dim=0)
        cp = torch.stack([to_gpu(c)  for c  in cp_np], dim=0)

        sigmas = torch.stack(
            [torch.as_tensor(iv[sl], dtype=dtype, device=device) for iv in iv_np],
            dim=0,
        )

        prices = bs_price_torch(S, K, T, r, cp, sigmas)

        for i in range(N):
            results[i][sl] = prices[i].cpu()

        del S, K, T, r, cp, sigmas, prices
        torch.cuda.empty_cache()

    return results

In [18]:
# Group data on day and cusip (underlying)
set_seed(42)
grouped_data = data.groupby(['date'])
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['price']

streams = {}
results = {}
for i, group in grouped_data:
    streams[i] = torch.cuda.Stream()
    results[i] = torch.empty(1,device="cuda")

for i, group in grouped_data:
    stream = streams[i]
    with torch.cuda.stream(stream):
        print(group["date"].unique())
        
        temp = XGB_function_surface(group, selected_columns_x, selected_columns_y, params=params_xgb_surface_price)
        results[i] = temp.copy()
    del temp, group
    torch.cuda.synchronize()
    torch.cuda.empty_cache()


for stream in streams.values():
    stream.synchronize()

surface_xgb_price_data = pd.concat(results.values())
surface_xgb_price_data

_oos = surface_xgb_price_data[surface_xgb_price_data["out_of_sample"] == 1]
print("mse:", mean_squared_error(_oos["price"], _oos["output_xgb"]))
print("rmse:", np.sqrt(mean_squared_error(_oos["price"], _oos["output_xgb"])))
print("mape:", mean_absolute_percentage_error(_oos["price"], _oos["output_xgb"]))
print("rsquared:", r2_score(_oos["price"], _oos["output_xgb"]))

surface_xgb_price_data = surface_xgb_price_data.rename(columns={"output_xgb":"price_xgb"})
surface_xgb_price_data

<DatetimeArray>
['2003-01-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 1082.26806640625
rmse: 32.89784288378571
mape: 1.8063726425170898
rsquared: 0.9040464162826538
<DatetimeArray>
['2003-01-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 81.2040023803711
rmse: 9.011326338579194
mape: 0.6717473864555359
rsquared: 0.9891369938850403
<DatetimeArray>
['2003-01-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 130.86659240722656
rmse: 11.439693719992095
mape: 0.8617540001869202
rsquared: 0.9866800308227539
<DatetimeArray>
['2003-01-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 279.05841064453125
rmse: 16.70504147389438
mape: 0.9343326091766357
rsquared: 0.973307192325592
<DatetimeArray>
['2003-01-08 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 106.22261047363281
rmse: 10.306435391231675
mape: 1.118148922920227
rsquared: 0.9856283664703369
<DatetimeArray>
['2003-01-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 142.76449584960938
rmse: 11.94840976237463
mape: 1.297647476196289
rsquared: 0.9839825630187988
<DatetimeArray>
['2003-01-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 188.9696044921875
rmse: 13.746621566486345
mape: 0.810322105884552
rsquared: 0.9809560179710388
<DatetimeArray>
['2003-01-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 81.87164306640625
rmse: 9.048295036436768
mape: 0.8307578563690186
rsquared: 0.9895153641700745
<DatetimeArray>
['2003-01-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 465.0552978515625
rmse: 21.565140802961675
mape: 1.3764362335205078
rsquared: 0.9758701324462891
<DatetimeArray>
['2003-01-15 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 119.9803237915039
rmse: 10.953553021349004
mape: 0.8620444536209106
rsquared: 0.9838438630104065
<DatetimeArray>
['2003-01-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 155.56259155273438
rmse: 12.472473353458582
mape: 0.5841089487075806
rsquared: 0.9848136305809021
<DatetimeArray>
['2003-01-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 129.08453369140625
rmse: 11.361537470404533
mape: 0.8809031248092651
rsquared: 0.9848857522010803
<DatetimeArray>
['2003-01-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 169.40509033203125
rmse: 13.015571072067152
mape: 0.5187733173370361
rsquared: 0.979676365852356
<DatetimeArray>
['2003-01-22 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 88.43580627441406
rmse: 9.40403138416786
mape: 0.947320818901062
rsquared: 0.990687370300293
<DatetimeArray>
['2003-01-23 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 219.4239044189453
rmse: 14.812964065943902
mape: 1.4444429874420166
rsquared: 0.9894487857818604
<DatetimeArray>
['2003-01-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 167.1449737548828
rmse: 12.928455969483858
mape: 0.8028454780578613
rsquared: 0.9889019727706909
<DatetimeArray>
['2003-01-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 309.9312744140625
rmse: 17.604865077985192
mape: 0.551106333732605
rsquared: 0.9748204946517944
<DatetimeArray>
['2003-01-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 426.4796447753906
rmse: 20.65138360438328
mape: 0.8132520318031311
rsquared: 0.9780782461166382
<DatetimeArray>
['2003-01-29 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 123.04508972167969
rmse: 11.092569121789582
mape: 0.9190212488174438
rsquared: 0.9879865050315857
<DatetimeArray>
['2003-01-30 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 188.68565368652344
rmse: 13.736289662296855
mape: 0.9194539189338684
rsquared: 0.9873901605606079
<DatetimeArray>
['2003-01-31 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 894.947021484375
rmse: 29.915665151963026
mape: 1.566650629043579
rsquared: 0.9336481094360352
<DatetimeArray>
['2003-02-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 463.0138244628906
rmse: 21.517756027590114
mape: 0.7610873579978943
rsquared: 0.9594456553459167
<DatetimeArray>
['2003-02-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 274.2699890136719
rmse: 16.561098665658385
mape: 0.5165292620658875
rsquared: 0.9673978686332703
<DatetimeArray>
['2003-02-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 148.0375518798828
rmse: 12.16706833546532
mape: 0.9345643520355225
rsquared: 0.9811089634895325
<DatetimeArray>
['2003-02-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 63.14080047607422
rmse: 7.946118579286003
mape: 0.6487383246421814
rsquared: 0.9890332818031311
<DatetimeArray>
['2003-02-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 160.81642150878906
rmse: 12.681341471184705
mape: 0.749305784702301
rsquared: 0.9796951413154602
<DatetimeArray>
['2003-02-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 82.90540313720703
rmse: 9.105240421713587
mape: 0.9107251167297363
rsquared: 0.9904035329818726
<DatetimeArray>
['2003-02-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 223.6883544921875
rmse: 14.95621457763252
mape: 0.7866747379302979
rsquared: 0.969851553440094
<DatetimeArray>
['2003-02-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 954.302001953125
rmse: 30.891778873239478
mape: 1.5612887144088745
rsquared: 0.9233952760696411
<DatetimeArray>
['2003-02-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 194.71463012695312
rmse: 13.954018422194846
mape: 0.7201899290084839
rsquared: 0.9719177484512329
<DatetimeArray>
['2003-02-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 196.05776977539062
rmse: 14.002063054257063
mape: 0.833992063999176
rsquared: 0.9777640104293823
<DatetimeArray>
['2003-02-18 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 695.0072021484375
rmse: 26.362989249105222
mape: 1.1265463829040527
rsquared: 0.9125548601150513
<DatetimeArray>
['2003-02-19 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 248.89759826660156
rmse: 15.776488781303701
mape: 0.4616575837135315
rsquared: 0.973584771156311
<DatetimeArray>
['2003-02-20 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 287.32147216796875
rmse: 16.950559641733626
mape: 0.48952528834342957
rsquared: 0.9640170931816101
<DatetimeArray>
['2003-02-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 861.8914794921875
rmse: 29.357988342054153
mape: 1.121593713760376
rsquared: 0.950581431388855
<DatetimeArray>
['2003-02-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 147.28955078125
rmse: 12.13629065164682
mape: 0.7987896800041199
rsquared: 0.9782306551933289
<DatetimeArray>
['2003-02-25 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 192.8533935546875
rmse: 13.887166505615445
mape: 0.9130392670631409
rsquared: 0.9832502603530884
<DatetimeArray>
['2003-02-26 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 185.00462341308594
rmse: 13.60164046771881
mape: 0.6486804485321045
rsquared: 0.9787428975105286
<DatetimeArray>
['2003-02-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 199.87510681152344
rmse: 14.13771929313648
mape: 0.934550940990448
rsquared: 0.9707514643669128
<DatetimeArray>
['2003-02-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 115.1012954711914
rmse: 10.728527180894469
mape: 0.9959059357643127
rsquared: 0.9863240718841553
<DatetimeArray>
['2003-03-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 103.38761138916016
rmse: 10.167969875504163
mape: 0.6299840211868286
rsquared: 0.9853687286376953
<DatetimeArray>
['2003-03-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 95.59750366210938
rmse: 9.777397591491786
mape: 0.7429615259170532
rsquared: 0.9869248270988464
<DatetimeArray>
['2003-03-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 1269.5098876953125
rmse: 35.63018225739678
mape: 1.10471773147583
rsquared: 0.9232930541038513
<DatetimeArray>
['2003-03-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 74.88639068603516
rmse: 8.653692315193275
mape: 1.4194241762161255
rsquared: 0.9872557520866394
<DatetimeArray>
['2003-03-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 840.3311157226562
rmse: 28.988465218473646
mape: 1.9697482585906982
rsquared: 0.9331032633781433
<DatetimeArray>
['2003-03-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 136.2031707763672
rmse: 11.67061141399058
mape: 1.843666672706604
rsquared: 0.9788054823875427
<DatetimeArray>
['2003-03-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 293.200439453125
rmse: 17.12309666658239
mape: 1.5673573017120361
rsquared: 0.9841344952583313
<DatetimeArray>
['2003-03-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 76.1252670288086
rmse: 8.724979485867493
mape: 0.7967445850372314
rsquared: 0.9878970384597778
<DatetimeArray>
['2003-03-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 121.6128921508789
rmse: 11.027823545508829
mape: 1.1401232481002808
rsquared: 0.9857798218727112
<DatetimeArray>
['2003-03-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 73.95487213134766
rmse: 8.599701862933834
mape: 0.6571374535560608
rsquared: 0.9880626797676086
<DatetimeArray>
['2003-03-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 317.04327392578125
rmse: 17.805709026202276
mape: 1.2256760597229004
rsquared: 0.9721455574035645
<DatetimeArray>
['2003-03-18 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 139.6180877685547
rmse: 11.816009807399226
mape: 0.9010990262031555
rsquared: 0.9863766431808472
<DatetimeArray>
['2003-03-19 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 197.57176208496094
rmse: 14.056022271075161
mape: 1.5685100555419922
rsquared: 0.9796521663665771
<DatetimeArray>
['2003-03-20 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 79.82337951660156
rmse: 8.934393069291364
mape: 0.7674604654312134
rsquared: 0.9900560975074768
<DatetimeArray>
['2003-03-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 508.3470764160156
rmse: 22.54655353742597
mape: 1.1538382768630981
rsquared: 0.9511215686798096
<DatetimeArray>
['2003-03-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 1243.7008056640625
rmse: 35.26614248346511
mape: 2.1016480922698975
rsquared: 0.8341716527938843
<DatetimeArray>
['2003-03-25 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 177.6245880126953
rmse: 13.327587479086203
mape: 1.1882799863815308
rsquared: 0.9792717695236206
<DatetimeArray>
['2003-03-26 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 112.72111511230469
rmse: 10.617020067434398
mape: 1.3421823978424072
rsquared: 0.9862176775932312
<DatetimeArray>
['2003-03-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 240.32896423339844
rmse: 15.502547024066672
mape: 0.5985109806060791
rsquared: 0.9726673364639282
<DatetimeArray>
['2003-03-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 106.33647155761719
rmse: 10.31195769762547
mape: 1.1552295684814453
rsquared: 0.9869540333747864
<DatetimeArray>
['2003-03-31 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 115.8838882446289
rmse: 10.764937911786992
mape: 0.649722158908844
rsquared: 0.9887240529060364
<DatetimeArray>
['2003-04-01 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 164.52850341796875
rmse: 12.826866469171991
mape: 1.3117862939834595
rsquared: 0.9872738718986511
<DatetimeArray>
['2003-04-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 80.97005462646484
rmse: 8.998336214349008
mape: 1.3213493824005127
rsquared: 0.9940068125724792
<DatetimeArray>
['2003-04-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 777.947265625
rmse: 27.891706036472563
mape: 1.1824753284454346
rsquared: 0.9554489850997925
<DatetimeArray>
['2003-04-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 80.00993347167969
rmse: 8.944827190710823
mape: 1.1202212572097778
rsquared: 0.9882569909095764
<DatetimeArray>
['2003-04-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 359.8223571777344
rmse: 18.968984083965445
mape: 1.136576771736145
rsquared: 0.9758187532424927
<DatetimeArray>
['2003-04-08 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 147.22499084472656
rmse: 12.133630571462383
mape: 1.817622184753418
rsquared: 0.9798696041107178
<DatetimeArray>
['2003-04-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 225.9508056640625
rmse: 15.031660110049804
mape: 1.0977760553359985
rsquared: 0.972429633140564
<DatetimeArray>
['2003-04-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 577.9334716796875
rmse: 24.04024691386691
mape: 1.25001859664917
rsquared: 0.9315792918205261
<DatetimeArray>
['2003-04-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 64.19031524658203
rmse: 8.011885873287389
mape: 0.6082517504692078
rsquared: 0.988837718963623
<DatetimeArray>
['2003-04-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 466.9454650878906
rmse: 21.60892096074884
mape: 0.6144903898239136
rsquared: 0.9392879605293274
<DatetimeArray>
['2003-04-15 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 108.77880096435547
rmse: 10.429707616436593
mape: 1.5721858739852905
rsquared: 0.9850297570228577
<DatetimeArray>
['2003-04-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 310.8524475097656
rmse: 17.631008125168727
mape: 1.165467619895935
rsquared: 0.9593674540519714
<DatetimeArray>
['2003-04-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 619.0509033203125
rmse: 24.88073357681225
mape: 0.805169403553009
rsquared: 0.9590321183204651
<DatetimeArray>
['2003-04-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 474.4794616699219
rmse: 21.782549475897486
mape: 1.8475961685180664
rsquared: 0.9316285848617554
<DatetimeArray>
['2003-04-22 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 278.1861572265625
rmse: 16.678913550545268
mape: 1.3037447929382324
rsquared: 0.9770312309265137
<DatetimeArray>
['2003-04-23 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 579.9417724609375
rmse: 24.08198024376188
mape: 0.9438682198524475
rsquared: 0.9348353147506714
<DatetimeArray>
['2003-04-24 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 142.99647521972656
rmse: 11.958113363726175
mape: 0.9427147507667542
rsquared: 0.9801653623580933
<DatetimeArray>
['2003-04-25 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 515.2967529296875
rmse: 22.70014874245734
mape: 1.8546953201293945
rsquared: 0.9043281674385071
<DatetimeArray>
['2003-04-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 266.5756530761719
rmse: 16.32714467003254
mape: 1.3064918518066406
rsquared: 0.959407389163971
<DatetimeArray>
['2003-04-29 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 392.9092102050781
rmse: 19.82193759966664
mape: 0.7873213291168213
rsquared: 0.9543171525001526
<DatetimeArray>
['2003-04-30 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 877.1353149414062
rmse: 29.61647033225611
mape: 0.9444952607154846
rsquared: 0.8950062394142151
<DatetimeArray>
['2003-05-01 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 339.6540832519531
rmse: 18.429706542751926
mape: 1.7030079364776611
rsquared: 0.9569573402404785
<DatetimeArray>
['2003-05-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 1103.7547607421875
rmse: 33.22280482954724
mape: 1.4147480726242065
rsquared: 0.931286633014679
<DatetimeArray>
['2003-05-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 693.46142578125
rmse: 26.333655761805083
mape: 2.3047664165496826
rsquared: 0.8804522156715393
<DatetimeArray>
['2003-05-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 103.747802734375
rmse: 10.185666533633182
mape: 1.0801405906677246
rsquared: 0.9803299307823181
<DatetimeArray>
['2003-05-07 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 495.7054138183594
rmse: 22.26444281401085
mape: 2.1441221237182617
rsquared: 0.9325834512710571
<DatetimeArray>
['2003-05-08 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 58.46848678588867
rmse: 7.646468909626761
mape: 0.7210599780082703
rsquared: 0.9875445365905762
<DatetimeArray>
['2003-05-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 193.8878173828125
rmse: 13.924360573570784
mape: 1.2096551656723022
rsquared: 0.9700186848640442
<DatetimeArray>
['2003-05-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 195.24337768554688
rmse: 13.972951645430784
mape: 0.8987219929695129
rsquared: 0.9795169830322266
<DatetimeArray>
['2003-05-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 49.06017303466797
rmse: 7.004296755183062
mape: 1.010542631149292
rsquared: 0.9920111298561096
<DatetimeArray>
['2003-05-14 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 159.21493530273438
rmse: 12.618040073748949
mape: 0.6344539523124695
rsquared: 0.9781064391136169
<DatetimeArray>
['2003-05-15 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 168.7378387451172
rmse: 12.989912961414221
mape: 0.8037652969360352
rsquared: 0.9753580689430237
<DatetimeArray>
['2003-05-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 141.6688995361328
rmse: 11.902474513147794
mape: 0.9092569351196289
rsquared: 0.9795557260513306
<DatetimeArray>
['2003-05-19 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 55.10486602783203
rmse: 7.423265186414401
mape: 0.9958191514015198
rsquared: 0.9904351830482483
<DatetimeArray>
['2003-05-20 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 114.18099975585938
rmse: 10.685550980452968
mape: 1.2367311716079712
rsquared: 0.9784519672393799
<DatetimeArray>
['2003-05-21 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 237.0906982421875
rmse: 15.397749778528922
mape: 2.108496904373169
rsquared: 0.9585577845573425
<DatetimeArray>
['2003-05-22 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 240.5309600830078
rmse: 15.50906058028686
mape: 1.1211577653884888
rsquared: 0.9642513990402222
<DatetimeArray>
['2003-05-23 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 312.1185302734375
rmse: 17.666876641711106
mape: 1.6304928064346313
rsquared: 0.959898054599762
<DatetimeArray>
['2003-05-27 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 228.8039093017578
rmse: 15.126265543806833
mape: 1.0217548608779907
rsquared: 0.9843713641166687
<DatetimeArray>
['2003-05-28 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 157.69219970703125
rmse: 12.557555482936607
mape: 1.5649782419204712
rsquared: 0.9815899133682251
<DatetimeArray>
['2003-05-29 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 170.08648681640625
rmse: 13.041721006692569
mape: 0.9258280992507935
rsquared: 0.9831843376159668
<DatetimeArray>
['2003-05-30 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 191.87564086914062
rmse: 13.8519183100804
mape: 1.0438132286071777
rsquared: 0.9749588966369629
<DatetimeArray>
['2003-06-02 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 275.7938537597656
rmse: 16.60704229415237
mape: 1.2712900638580322
rsquared: 0.9729436039924622
<DatetimeArray>
['2003-06-03 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 98.05724334716797
rmse: 9.902385740172313
mape: 0.6860051155090332
rsquared: 0.9884078502655029
<DatetimeArray>
['2003-06-04 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 36.78432083129883
rmse: 6.065007900349251
mape: 0.6282513737678528
rsquared: 0.9946189522743225
<DatetimeArray>
['2003-06-05 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 438.60595703125
rmse: 20.94292140631889
mape: 1.8899006843566895
rsquared: 0.9554908871650696
<DatetimeArray>
['2003-06-06 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 40.461936950683594
rmse: 6.360969812118557
mape: 0.7864298820495605
rsquared: 0.9913702607154846
<DatetimeArray>
['2003-06-09 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 466.07867431640625
rmse: 21.588855326682012
mape: 1.717637300491333
rsquared: 0.9380297660827637
<DatetimeArray>
['2003-06-10 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 287.952392578125
rmse: 16.96916004338827
mape: 1.3169573545455933
rsquared: 0.9737816452980042
<DatetimeArray>
['2003-06-11 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 350.7399597167969
rmse: 18.72805274759757
mape: 0.8894065618515015
rsquared: 0.9661049246788025
<DatetimeArray>
['2003-06-12 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 331.0316162109375
rmse: 18.19427426997124
mape: 0.4644608795642853
rsquared: 0.9688126444816589
<DatetimeArray>
['2003-06-13 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 87.51380157470703
rmse: 9.354881163045688
mape: 0.8421465158462524
rsquared: 0.9894031882286072
<DatetimeArray>
['2003-06-16 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 351.94586181640625
rmse: 18.76022019637313
mape: 6.048426628112793
rsquared: 0.957436740398407
<DatetimeArray>
['2003-06-17 00:00:00']
Length: 1, dtype: datetime64[ms]
mse: 1070.1226806640625

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,impl_volatility,ddelta,...,stock_price,realized_vol,moneyness,price,price_xgb,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2003-01-02,2003-02-22,C,90.0,1.30,1.50,1464.0,5083.0,0.233642,0.309251,...,86.08,0.030519,0.044533,1.400,-2.720566,0,1082.268066,32.897843,1.806373,0.904046
1,2003-01-02,2003-02-22,C,91.0,0.95,1.15,255.0,540.0,0.224751,0.256302,...,86.08,0.030519,0.055582,1.050,-3.884384,1,1082.268066,32.897843,1.806373,0.904046
2,2003-01-02,2003-02-22,C,92.0,0.75,0.95,0.0,355.0,0.225981,0.216934,...,86.08,0.030519,0.066511,0.850,-3.884384,1,1082.268066,32.897843,1.806373,0.904046
3,2003-01-02,2003-02-22,C,94.0,0.40,0.55,0.0,835.0,0.218488,0.139982,...,86.08,0.030519,0.088018,0.475,-5.893448,0,1082.268066,32.897843,1.806373,0.904046
4,2003-01-02,2003-03-22,C,90.0,2.15,2.45,2028.0,13151.0,0.250788,0.361403,...,86.08,0.048298,0.044533,2.300,0.022400,0,1082.268066,32.897843,1.806373,0.904046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163837,2003-12-31,2004-09-18,P,975.0,20.10,22.10,0.0,744.0,0.196156,-0.191240,...,1111.92,0.093558,-0.131406,21.100,20.967663,1,190.018661,13.784726,1.247661,0.961253
163838,2003-12-31,2004-09-18,P,995.0,23.50,25.50,607.0,4679.0,0.189753,-0.220435,...,1111.92,0.093558,-0.111101,24.500,23.015650,0,190.018661,13.784726,1.247661,0.961253
163839,2003-12-31,2004-09-18,P,900.0,11.50,13.10,3150.0,4822.0,0.222397,-0.111764,...,1111.92,0.093558,-0.211449,12.300,9.794445,1,190.018661,13.784726,1.247661,0.961253
163840,2003-12-31,2004-03-20,P,1500.0,387.50,389.50,0.0,13601.0,0.270825,-0.986928,...,1111.92,0.023402,0.299377,388.500,273.891052,1,190.018661,13.784726,1.247661,0.961253
163841,2003-12-31,2004-06-19,P,1500.0,387.20,389.20,0.0,326.0,0.193454,-0.979654,...,1111.92,0.059106,0.299377,388.200,314.975342,1,190.018661,13.784726,1.247661,0.961253

In [19]:
### LBFGS Torch ANN surface estimation through Option price modelling
set_seed(42)
grouped_data = data.groupby(['date'])
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['price']
ignore = ["cp_flag_one"]

streams = {}
results = {}
for i, group in grouped_data:
    streams[i] = torch.cuda.Stream()
    results[i] = torch.empty(1,device="cuda")

for i, group in grouped_data:
    stream = streams[i]
    with torch.cuda.stream(stream):
        print(group["date"].unique())
        
        temp = ANN_function_torch_LBFGS_surface(group, selected_columns_x, selected_columns_y, ignore, log_y=True, params=params_lbfgs_surface_price)
        results[i] = temp.copy()
    del temp, group
    torch.cuda.synchronize()
    torch.cuda.empty_cache()


for stream in streams.values():
    stream.synchronize()

surface_ann_lbfgs_price_data = pd.concat(results.values())
surface_ann_lbfgs_price_data

_oos = surface_ann_lbfgs_price_data[surface_ann_lbfgs_price_data["out_of_sample"] == 1]
print("mse:", mean_squared_error(_oos["price"], _oos["output_ann"]))
print("rmse:", np.sqrt(mean_squared_error(_oos["price"], _oos["output_ann"])))
print("mape:", mean_absolute_percentage_error(_oos["price"], _oos["output_ann"]))
print("rsquared:", r2_score(_oos["price"], _oos["output_ann"]))

surface_ann_lbfgs_price_data = surface_ann_lbfgs_price_data.rename(columns={"output_ann":"price_ann"})
surface_ann_lbfgs_price_data

<DatetimeArray>
['2003-01-02 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.4325
Run 001 | Training Loss: 0.0365
Run 002 | Training Loss: 0.0056
Run 003 | Training Loss: 0.0027
Run 004 | Training Loss: 0.0017
mse: 10.50755388043554
rmse: 3.241535728699522
mape: 0.03391736883154761
rsquared: 0.9990684034020044
<DatetimeArray>
['2003-01-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.0657
Run 001 | Training Loss: 0.0257
Run 002 | Training Loss: 0.0082
Run 003 | Training Loss: 0.0036
Run 004 | Training Loss: 0.0025
mse: 27.199087898507045
rmse: 5.21527447969012
mape: 0.036046501950864035
rsquared: 0.99636146482467
<DatetimeArray>
['2003-01-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.8670
Run 001 | Training Loss: 0.0296
Run 002 | Training Loss: 0.0078
Run 003 | Training Loss: 0.0038
Run 004 | Training Loss: 0.0023
mse: 15.413563087775083
rmse: 3.9260110911426476
mape: 0.0424648986437505
rsquared: 0.9984311652269223
<DatetimeArray>
['2003-01-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.6506
Run 001 | Training Loss: 0.0291
Run 002 | Training Loss: 0.0055
Run 003 | Training Loss: 0.0029
Run 004 | Training Loss: 0.0018
mse: 17.973005578312815
rmse: 4.239458170369512
mape: 0.03291573465430781
rsquared: 0.9982808255802621
<DatetimeArray>
['2003-01-08 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.8678
Run 001 | Training Loss: 0.0216
Run 002 | Training Loss: 0.0065
Run 003 | Training Loss: 0.0032
Run 004 | Training Loss: 0.0023
mse: 12.981256154397965
rmse: 3.602951034138261
mape: 0.04517860691683857
rsquared: 0.9982436688875174
<DatetimeArray>
['2003-01-09 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.9057
Run 001 | Training Loss: 0.0418
Run 002 | Training Loss: 0.0108
Run 003 | Training Loss: 0.0044
Run 004 | Training Loss: 0.0028
mse: 18.457811223215714
rmse: 4.296255488587208
mape: 0.04359104732972158
rsquared: 0.9979291283591566
<DatetimeArray>
['2003-01-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.5084
Run 001 | Training Loss: 0.0479
Run 002 | Training Loss: 0.0107
Run 003 | Training Loss: 0.0050
Run 004 | Training Loss: 0.0027
mse: 43.89187518352018
rmse: 6.625094352801338
mape: 0.04103791832786775
rsquared: 0.9955766583184755
<DatetimeArray>
['2003-01-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.6391
Run 001 | Training Loss: 0.0203
Run 002 | Training Loss: 0.0053
Run 003 | Training Loss: 0.0025
Run 004 | Training Loss: 0.0014
mse: 15.45157088109098
rmse: 3.9308486209838938
mape: 0.02907605323138086
rsquared: 0.9980212436803794
<DatetimeArray>
['2003-01-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.3755
Run 001 | Training Loss: 0.0318
Run 002 | Training Loss: 0.0071
Run 003 | Training Loss: 0.0029
Run 004 | Training Loss: 0.0014
mse: 89.5143674504385
rmse: 9.461203277091053
mape: 0.033279192176286
rsquared: 0.995355454317051
<DatetimeArray>
['2003-01-15 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.5649
Run 001 | Training Loss: 0.0248
Run 002 | Training Loss: 0.0058
Run 003 | Training Loss: 0.0027
Run 004 | Training Loss: 0.0016
mse: 5.041140879008439
rmse: 2.2452485116370613
mape: 0.030582890390348377
rsquared: 0.9993211768866632
<DatetimeArray>
['2003-01-16 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.9403
Run 001 | Training Loss: 0.0202
Run 002 | Training Loss: 0.0043
Run 003 | Training Loss: 0.0014
Run 004 | Training Loss: 0.0008
mse: 30.533641569749864
rmse: 5.525725433800512
mape: 0.021136287230400463
rsquared: 0.9970192329584698
<DatetimeArray>
['2003-01-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.3943
Run 001 | Training Loss: 0.0157
Run 002 | Training Loss: 0.0031
Run 003 | Training Loss: 0.0012
Run 004 | Training Loss: 0.0007
mse: 18.702810597085676
rmse: 4.3246746232619255
mape: 0.031005256392815272
rsquared: 0.9978101282091654
<DatetimeArray>
['2003-01-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.5822
Run 001 | Training Loss: 0.0303
Run 002 | Training Loss: 0.0054
Run 003 | Training Loss: 0.0022
Run 004 | Training Loss: 0.0015
mse: 10.825963074324854
rmse: 3.2902831298119093
mape: 0.02424205553536247
rsquared: 0.9987012035329829
<DatetimeArray>
['2003-01-22 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.9675
Run 001 | Training Loss: 0.0262
Run 002 | Training Loss: 0.0064
Run 003 | Training Loss: 0.0028
Run 004 | Training Loss: 0.0013
mse: 8.41104360970266
rmse: 2.9001799271256705
mape: 0.0275700432200232
rsquared: 0.9991142820538189
<DatetimeArray>
['2003-01-23 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.3334
Run 001 | Training Loss: 0.0406
Run 002 | Training Loss: 0.0090
Run 003 | Training Loss: 0.0039
Run 004 | Training Loss: 0.0018
mse: 12.978638421775495
rmse: 3.602587739635982
mape: 0.027931186309715337
rsquared: 0.9993759085748999
<DatetimeArray>
['2003-01-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.8073
Run 001 | Training Loss: 0.0193
Run 002 | Training Loss: 0.0053
Run 003 | Training Loss: 0.0024
Run 004 | Training Loss: 0.0013
mse: 19.70533948527025
rmse: 4.439069664385799
mape: 0.02729538755224829
rsquared: 0.9986916131686646
<DatetimeArray>
['2003-01-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.7293
Run 001 | Training Loss: 0.0172
Run 002 | Training Loss: 0.0058
Run 003 | Training Loss: 0.0022
Run 004 | Training Loss: 0.0012
mse: 12.117386070349248
rmse: 3.481003601025033
mape: 0.022514982198675246
rsquared: 0.9990155575068093
<DatetimeArray>
['2003-01-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.1884
Run 001 | Training Loss: 0.0311
Run 002 | Training Loss: 0.0080
Run 003 | Training Loss: 0.0032
Run 004 | Training Loss: 0.0016
mse: 95.18038542473661
rmse: 9.756043533355959
mape: 0.027746837313608122
rsquared: 0.9951075704810595
<DatetimeArray>
['2003-01-29 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.8529
Run 001 | Training Loss: 0.0369
Run 002 | Training Loss: 0.0050
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0012
mse: 35.90669668254792
rmse: 5.992219679096213
mape: 0.031423714675090204
rsquared: 0.9964942617556694
<DatetimeArray>
['2003-01-30 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.4279
Run 001 | Training Loss: 0.0502
Run 002 | Training Loss: 0.0057
Run 003 | Training Loss: 0.0022
Run 004 | Training Loss: 0.0012
mse: 9.778282820323158
rmse: 3.1270245954138507
mape: 0.03154378233684483
rsquared: 0.9993465181225449
<DatetimeArray>
['2003-01-31 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.0652
Run 001 | Training Loss: 0.0306
Run 002 | Training Loss: 0.0065
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0011
mse: 12.180028664749086
rmse: 3.4899897800350486
mape: 0.023944863046977023
rsquared: 0.9990969657479453
<DatetimeArray>
['2003-02-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.1050
Run 001 | Training Loss: 0.0170
Run 002 | Training Loss: 0.0026
Run 003 | Training Loss: 0.0010
Run 004 | Training Loss: 0.0006
mse: 11.929667074649146
rmse: 3.4539350130900184
mape: 0.01966474313934236
rsquared: 0.9989551068711688
<DatetimeArray>
['2003-02-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.2195
Run 001 | Training Loss: 0.0274
Run 002 | Training Loss: 0.0054
Run 003 | Training Loss: 0.0022
Run 004 | Training Loss: 0.0013
mse: 25.616559202375004
rmse: 5.061280391598059
mape: 0.02850043993671611
rsquared: 0.9969549910419021
<DatetimeArray>
['2003-02-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 10.8963
Run 001 | Training Loss: 0.0176
Run 002 | Training Loss: 0.0046
Run 003 | Training Loss: 0.0018
Run 004 | Training Loss: 0.0010
mse: 14.208812754532278
rmse: 3.7694578860271513
mape: 0.02905429152967871
rsquared: 0.9981868192081909
<DatetimeArray>
['2003-02-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.8407
Run 001 | Training Loss: 0.0263
Run 002 | Training Loss: 0.0051
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0012
mse: 11.391883453180435
rmse: 3.375186432359024
mape: 0.03181352504382676
rsquared: 0.9980213827226873
<DatetimeArray>
['2003-02-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.5284
Run 001 | Training Loss: 0.0361
Run 002 | Training Loss: 0.0075
Run 003 | Training Loss: 0.0030
Run 004 | Training Loss: 0.0016
mse: 17.309685793313463
rmse: 4.160491051944886
mape: 0.03242322210438557
rsquared: 0.9978144583695828
<DatetimeArray>
['2003-02-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.8047
Run 001 | Training Loss: 0.0320
Run 002 | Training Loss: 0.0055
Run 003 | Training Loss: 0.0029
Run 004 | Training Loss: 0.0017
mse: 14.018659917784348
rmse: 3.7441500928494236
mape: 0.03464309153333884
rsquared: 0.9983773140127993
<DatetimeArray>
['2003-02-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.8472
Run 001 | Training Loss: 0.0290
Run 002 | Training Loss: 0.0059
Run 003 | Training Loss: 0.0022
Run 004 | Training Loss: 0.0012
mse: 10.680355636112143
rmse: 3.268081338662204
mape: 0.022791387920135874
rsquared: 0.9985605145949829
<DatetimeArray>
['2003-02-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.3048
Run 001 | Training Loss: 0.0338
Run 002 | Training Loss: 0.0041
Run 003 | Training Loss: 0.0015
Run 004 | Training Loss: 0.0009
mse: 12.682405490098871
rmse: 3.561236511395848
mape: 0.021467118184557835
rsquared: 0.9989819443811744
<DatetimeArray>
['2003-02-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 10.5906
Run 001 | Training Loss: 0.0333
Run 002 | Training Loss: 0.0084
Run 003 | Training Loss: 0.0027
Run 004 | Training Loss: 0.0015
mse: 16.067171753261615
rmse: 4.0083876750211695
mape: 0.033848233217235284
rsquared: 0.9976827506092716
<DatetimeArray>
['2003-02-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 10.8035
Run 001 | Training Loss: 0.0317
Run 002 | Training Loss: 0.0064
Run 003 | Training Loss: 0.0028
Run 004 | Training Loss: 0.0017
mse: 58.55923122881395
rmse: 7.65240035732671
mape: 0.03035668151699043
rsquared: 0.9933584761831853
<DatetimeArray>
['2003-02-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.2696
Run 001 | Training Loss: 0.0194
Run 002 | Training Loss: 0.0044
Run 003 | Training Loss: 0.0016
Run 004 | Training Loss: 0.0009
mse: 4.3536363192207315
rmse: 2.0865369201671777
mape: 0.023228686903495943
rsquared: 0.9994522294255941
<DatetimeArray>
['2003-02-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 10.8547
Run 001 | Training Loss: 0.0285
Run 002 | Training Loss: 0.0050
Run 003 | Training Loss: 0.0020
Run 004 | Training Loss: 0.0011
mse: 23.45772956395772
rmse: 4.843318032501863
mape: 0.02389842581614517
rsquared: 0.9975104555527364
<DatetimeArray>
['2003-02-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.3887
Run 001 | Training Loss: 0.0240
Run 002 | Training Loss: 0.0043
Run 003 | Training Loss: 0.0016
Run 004 | Training Loss: 0.0009
mse: 8.992416472971232
rmse: 2.9987358124668524
mape: 0.023341938421567097
rsquared: 0.9988738281452145
<DatetimeArray>
['2003-02-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 14.7308
Run 001 | Training Loss: 0.0420
Run 002 | Training Loss: 0.0075
Run 003 | Training Loss: 0.0034
Run 004 | Training Loss: 0.0019
mse: 34.12138499533093
rmse: 5.841351298743376
mape: 0.033643956482343675
rsquared: 0.9980435694752823
<DatetimeArray>
['2003-02-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.0700
Run 001 | Training Loss: 0.0248
Run 002 | Training Loss: 0.0051
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0012
mse: 19.702199375928725
rmse: 4.438715960266969
mape: 0.0326329321927942
rsquared: 0.9970880216567443
<DatetimeArray>
['2003-02-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.2053
Run 001 | Training Loss: 0.0215
Run 002 | Training Loss: 0.0050
Run 003 | Training Loss: 0.0019
Run 004 | Training Loss: 0.0010
mse: 6.550699045180111
rmse: 2.559433344547209
mape: 0.030937313941026657
rsquared: 0.9994310582541321
<DatetimeArray>
['2003-02-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 15.6678
Run 001 | Training Loss: 0.0167
Run 002 | Training Loss: 0.0034
Run 003 | Training Loss: 0.0015
Run 004 | Training Loss: 0.0009
mse: 17.29320735145403
rmse: 4.158510232217065
mape: 0.03103774901385199
rsquared: 0.9980130026266459
<DatetimeArray>
['2003-02-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.2584
Run 001 | Training Loss: 0.0308
Run 002 | Training Loss: 0.0063
Run 003 | Training Loss: 0.0025
Run 004 | Training Loss: 0.0015
mse: 7.674129811355474
rmse: 2.7702219787149684
mape: 0.031647388889004306
rsquared: 0.998877013529495
<DatetimeArray>
['2003-02-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.2934
Run 001 | Training Loss: 0.0291
Run 002 | Training Loss: 0.0050
Run 003 | Training Loss: 0.0024
Run 004 | Training Loss: 0.0016
mse: 6.898040890128971
rmse: 2.6264121706481967
mape: 0.032917532219056016
rsquared: 0.9991804005332561
<DatetimeArray>
['2003-03-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 10.0948
Run 001 | Training Loss: 0.0602
Run 002 | Training Loss: 0.0093
Run 003 | Training Loss: 0.0039
Run 004 | Training Loss: 0.0019
mse: 7.648929151831923
rmse: 2.7656697474268186
mape: 0.03615182484080621
rsquared: 0.998917532769533
<DatetimeArray>
['2003-03-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.6147
Run 001 | Training Loss: 0.0265
Run 002 | Training Loss: 0.0054
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0014
mse: 7.16480920229531
rmse: 2.6767161228444287
mape: 0.028007051539151805
rsquared: 0.9990200451038441
<DatetimeArray>
['2003-03-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.8812
Run 001 | Training Loss: 0.0332
Run 002 | Training Loss: 0.0066
Run 003 | Training Loss: 0.0025
Run 004 | Training Loss: 0.0014
mse: 212.36078733457418
rmse: 14.572603999785837
mape: 0.03291957673480186
rsquared: 0.9871686341980411
<DatetimeArray>
['2003-03-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.0194
Run 001 | Training Loss: 0.0568
Run 002 | Training Loss: 0.0080
Run 003 | Training Loss: 0.0025
Run 004 | Training Loss: 0.0014
mse: 7.4558900759993145
rmse: 2.730547578050841
mape: 0.031389340670463776
rsquared: 0.9987311512651775
<DatetimeArray>
['2003-03-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.2491
Run 001 | Training Loss: 0.0322
Run 002 | Training Loss: 0.0065
Run 003 | Training Loss: 0.0031
Run 004 | Training Loss: 0.0015
mse: 15.519926582781277
rmse: 3.9395338027209865
mape: 0.03241677075385703
rsquared: 0.998764495822134
<DatetimeArray>
['2003-03-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.3367
Run 001 | Training Loss: 0.0334
Run 002 | Training Loss: 0.0068
Run 003 | Training Loss: 0.0023
Run 004 | Training Loss: 0.0014
mse: 27.088980693865953
rmse: 5.204707551233398
mape: 0.038325324241713636
rsquared: 0.9957847002218682
<DatetimeArray>
['2003-03-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 13.4332
Run 001 | Training Loss: 0.0369
Run 002 | Training Loss: 0.0087
Run 003 | Training Loss: 0.0033
Run 004 | Training Loss: 0.0018
mse: 30.43173357536111
rmse: 5.516496494638704
mape: 0.0376390679141262
rsquared: 0.9983532932702537
<DatetimeArray>
['2003-03-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.4312
Run 001 | Training Loss: 0.0390
Run 002 | Training Loss: 0.0078
Run 003 | Training Loss: 0.0032
Run 004 | Training Loss: 0.0015
mse: 4.175802185210774
rmse: 2.043477962986333
mape: 0.03341495305505155
rsquared: 0.9993360983065025
<DatetimeArray>
['2003-03-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 10.7602
Run 001 | Training Loss: 0.0276
Run 002 | Training Loss: 0.0051
Run 003 | Training Loss: 0.0025
Run 004 | Training Loss: 0.0014
mse: 11.82133970292223
rmse: 3.4382175182676025
mape: 0.029890258841002305
rsquared: 0.9986177311274375
<DatetimeArray>
['2003-03-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.9990
Run 001 | Training Loss: 0.0449
Run 002 | Training Loss: 0.0058
Run 003 | Training Loss: 0.0027
Run 004 | Training Loss: 0.0016
mse: 12.141733945757498
rmse: 3.484499095387671
mape: 0.026901284632306847
rsquared: 0.9980401559950024
<DatetimeArray>
['2003-03-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.2048
Run 001 | Training Loss: 0.0114
Run 002 | Training Loss: 0.0023
Run 003 | Training Loss: 0.0011
Run 004 | Training Loss: 0.0008
mse: 8.00281882527661
rmse: 2.8289253834763137
mape: 0.02301742502694525
rsquared: 0.999296896922967
<DatetimeArray>
['2003-03-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.9800
Run 001 | Training Loss: 0.0204
Run 002 | Training Loss: 0.0048
Run 003 | Training Loss: 0.0026
Run 004 | Training Loss: 0.0015
mse: 14.31975635527221
rmse: 3.7841453929879876
mape: 0.026170662624072482
rsquared: 0.9986027348199117
<DatetimeArray>
['2003-03-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.9847
Run 001 | Training Loss: 0.0176
Run 002 | Training Loss: 0.0040
Run 003 | Training Loss: 0.0019
Run 004 | Training Loss: 0.0011
mse: 10.561279274203098
rmse: 3.2498121906047275
mape: 0.02802401415688479
rsquared: 0.9989122995396
<DatetimeArray>
['2003-03-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.0643
Run 001 | Training Loss: 0.0187
Run 002 | Training Loss: 0.0037
Run 003 | Training Loss: 0.0018
Run 004 | Training Loss: 0.0011
mse: 9.006321775378833
rmse: 3.001053444272333
mape: 0.027083152385526995
rsquared: 0.9988780452790674
<DatetimeArray>
['2003-03-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.2576
Run 001 | Training Loss: 0.0242
Run 002 | Training Loss: 0.0048
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0015
mse: 11.300031254903518
rmse: 3.3615519116776285
mape: 0.02770023506093234
rsquared: 0.9989134831138888
<DatetimeArray>
['2003-03-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.6895
Run 001 | Training Loss: 0.0177
Run 002 | Training Loss: 0.0052
Run 003 | Training Loss: 0.0021
Run 004 | Training Loss: 0.0010
mse: 6.035150634362532
rmse: 2.456654357935306
mape: 0.02142624045182672
rsquared: 0.9991953055240703
<DatetimeArray>
['2003-03-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 14.3962
Run 001 | Training Loss: 0.0168
Run 002 | Training Loss: 0.0043
Run 003 | Training Loss: 0.0019
Run 004 | Training Loss: 0.0011
mse: 3.9276556396415234
rmse: 1.9818313852700797
mape: 0.03245264579581878
rsquared: 0.9995416552058467
<DatetimeArray>
['2003-03-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.8830
Run 001 | Training Loss: 0.0186
Run 002 | Training Loss: 0.0044
Run 003 | Training Loss: 0.0022
Run 004 | Training Loss: 0.0014
mse: 17.78478875351256
rmse: 4.21720153105262
mape: 0.03160854376744474
rsquared: 0.9978254673475133
<DatetimeArray>
['2003-03-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 11.7392
Run 001 | Training Loss: 0.0169
Run 002 | Training Loss: 0.0054
Run 003 | Training Loss: 0.0020
Run 004 | Training Loss: 0.0011
mse: 7.823828777842682
rmse: 2.797110791127638
mape: 0.020878609073093038
rsquared: 0.9991101943528753
<DatetimeArray>
['2003-03-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.7103

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,impl_volatility,ddelta,...,stock_price,realized_vol,moneyness,price,price_ann,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2003-01-02,2003-02-22,C,90.0,1.30,1.50,1464.0,5083.0,0.233642,0.309251,...,86.08,0.030519,0.044533,1.400,1.379450,0,10.507554,3.241536,0.033917,0.999068
1,2003-01-02,2003-02-22,C,91.0,0.95,1.15,255.0,540.0,0.224751,0.256302,...,86.08,0.030519,0.055582,1.050,1.080765,1,10.507554,3.241536,0.033917,0.999068
2,2003-01-02,2003-02-22,C,92.0,0.75,0.95,0.0,355.0,0.225981,0.216934,...,86.08,0.030519,0.066511,0.850,0.834318,1,10.507554,3.241536,0.033917,0.999068
3,2003-01-02,2003-02-22,C,94.0,0.40,0.55,0.0,835.0,0.218488,0.139982,...,86.08,0.030519,0.088018,0.475,0.477074,0,10.507554,3.241536,0.033917,0.999068
4,2003-01-02,2003-03-22,C,90.0,2.15,2.45,2028.0,13151.0,0.250788,0.361403,...,86.08,0.048298,0.044533,2.300,2.302574,0,10.507554,3.241536,0.033917,0.999068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163837,2003-12-31,2004-09-18,P,975.0,20.10,22.10,0.0,744.0,0.196156,-0.191240,...,1111.92,0.093558,-0.131406,21.100,21.511543,1,25.067427,5.006738,0.037546,0.994889
163838,2003-12-31,2004-09-18,P,995.0,23.50,25.50,607.0,4679.0,0.189753,-0.220435,...,1111.92,0.093558,-0.111101,24.500,24.965252,0,25.067427,5.006738,0.037546,0.994889
163839,2003-12-31,2004-09-18,P,900.0,11.50,13.10,3150.0,4822.0,0.222397,-0.111764,...,1111.92,0.093558,-0.211449,12.300,12.271599,1,25.067427,5.006738,0.037546,0.994889
163840,2003-12-31,2004-03-20,P,1500.0,387.50,389.50,0.0,13601.0,0.270825,-0.986928,...,1111.92,0.023402,0.299377,388.500,338.564056,1,25.067427,5.006738,0.037546,0.994889
163841,2003-12-31,2004-06-19,P,1500.0,387.20,389.20,0.0,326.0,0.193454,-0.979654,...,1111.92,0.059106,0.299377,388.200,354.413177,1,25.067427,5.006738,0.037546,0.994889

In [22]:
# ANN torch LBGFS price
set_seed(42)

_p        = params_lbfgs_variable_price
_n_units  = _p.get('n_units',     64)
_n_layers = _p.get('n_layers',    3)
_max_iter = _p.get('max_iter',    20)
_hist_sz  = _p.get('history_size', 1)
device    = torch.device("cuda")


grouped_data = data.groupby(['date'])
selected_columns_x = ['cp_flag_one', 'time_to_mat', 'rf', 'stock_price', 'realized_vol', 'moneyness']
selected_columns_y = ['price']
ignore = ["cp_flag_one"]


_lrs = [nn.Linear(len(selected_columns_x), _n_units), nn.GELU()]
for _ in range(_n_layers - 1):
    _lrs += [nn.Linear(_n_units, _n_units), nn.GELU()]
_lrs.append(nn.Linear(_n_units, 1))
model = nn.Sequential(*_lrs).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.LBFGS(
    model.parameters(),
    max_iter=_max_iter,
    history_size=_hist_sz,
    line_search_fn="strong_wolfe"
)


results = {}

for i, group in grouped_data:
    print(group["date"].unique())
    
    temp = ANN_function_torch_LBFGS_variable(group, selected_columns_x, selected_columns_y, ignore, model=model, criterion=criterion, optimizer=optimizer, log_y=True)
    results[i] = temp.copy()
    del temp, group
    torch.cuda.synchronize()
    torch.cuda.empty_cache()



variable_ann_lbfgs_price_data = pd.concat(results.values())
variable_ann_lbfgs_price_data

_oos = variable_ann_lbfgs_price_data[variable_ann_lbfgs_price_data["out_of_sample"] == 1]
print("mse:", mean_squared_error(_oos["price"], _oos["output_ann"]))
print("rmse:", np.sqrt(mean_squared_error(_oos["price"], _oos["output_ann"])))
print("mape:", mean_absolute_percentage_error(_oos["price"], _oos["output_ann"]))
print("rsquared:", r2_score(_oos["price"], _oos["output_ann"]))

variable_ann_lbfgs_price_data = variable_ann_lbfgs_price_data.rename(columns={"output_ann":"price_ann"})
variable_ann_lbfgs_price_data

<DatetimeArray>
['2003-01-02 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 12.4499
Run 001 | Training Loss: 1.4876
Run 002 | Training Loss: 0.2008
Run 003 | Training Loss: 0.0579
Run 004 | Training Loss: 0.0271
mse: 190.0277071655713
rmse: 13.78505375998118
mape: 0.10865462022112665
rsquared: 0.983152200071039
<DatetimeArray>
['2003-01-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2603
Run 001 | Training Loss: 0.0147
Run 002 | Training Loss: 0.0112
Run 003 | Training Loss: 0.0089
Run 004 | Training Loss: 0.0062
mse: 32.858221162218825
rmse: 5.732209099659469
mape: 0.04577333061113538
rsquared: 0.9956044190178867
<DatetimeArray>
['2003-01-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2821
Run 001 | Training Loss: 0.0086
Run 002 | Training Loss: 0.0057
Run 003 | Training Loss: 0.0042
Run 004 | Training Loss: 0.0036
mse: 17.630964827723194
rmse: 4.198924246485425
mape: 0.057914694625427886
rsquared: 0.9982054719893689
<DatetimeArray>
['2003-01-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.4632
Run 001 | Training Loss: 0.0078
Run 002 | Training Loss: 0.0051
Run 003 | Training Loss: 0.0040
Run 004 | Training Loss: 0.0037
mse: 36.1139674560384
rmse: 6.009489783337551
mape: 0.04526533216422735
rsquared: 0.9965455856130939
<DatetimeArray>
['2003-01-08 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0419
Run 001 | Training Loss: 0.0034
Run 002 | Training Loss: 0.0028
Run 003 | Training Loss: 0.0024
Run 004 | Training Loss: 0.0021
mse: 12.765022395853107
rmse: 3.5728171511921945
mape: 0.04088316802274173
rsquared: 0.9982729247679333
<DatetimeArray>
['2003-01-09 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.4322
Run 001 | Training Loss: 0.0068
Run 002 | Training Loss: 0.0034
Run 003 | Training Loss: 0.0028
Run 004 | Training Loss: 0.0023
mse: 14.155903852920309
rmse: 3.762433235676124
mape: 0.04360371649754184
rsquared: 0.9984117802763826
<DatetimeArray>
['2003-01-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.5476
Run 001 | Training Loss: 0.0060
Run 002 | Training Loss: 0.0035
Run 003 | Training Loss: 0.0027
Run 004 | Training Loss: 0.0022
mse: 16.02177152388752
rmse: 4.002720515335478
mape: 0.036383908103654355
rsquared: 0.9983853556154265
<DatetimeArray>
['2003-01-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.7131
Run 001 | Training Loss: 0.0043
Run 002 | Training Loss: 0.0020
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0011
mse: 8.469525975452765
rmse: 2.9102450026505955
mape: 0.027420960190206126
rsquared: 0.9989153770722026
<DatetimeArray>
['2003-01-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1560
Run 001 | Training Loss: 0.0019
Run 002 | Training Loss: 0.0013
Run 003 | Training Loss: 0.0009
Run 004 | Training Loss: 0.0008
mse: 32.412483488252185
rmse: 5.693196245366234
mape: 0.024933437303997816
rsquared: 0.9983182447181748
<DatetimeArray>
['2003-01-15 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2586
Run 001 | Training Loss: 0.0018
Run 002 | Training Loss: 0.0010
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0007
mse: 5.719993704271455
rmse: 2.3916508324317443
mape: 0.02638082912869144
rsquared: 0.9992297648433573
<DatetimeArray>
['2003-01-16 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0119
Run 001 | Training Loss: 0.0011
Run 002 | Training Loss: 0.0008
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 5.998072087133788
rmse: 2.449096177599767
mape: 0.01938853800687116
rsquared: 0.9994144538721591
<DatetimeArray>
['2003-01-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0561
Run 001 | Training Loss: 0.0022
Run 002 | Training Loss: 0.0013
Run 003 | Training Loss: 0.0009
Run 004 | Training Loss: 0.0008
mse: 5.719811780766177
rmse: 2.39161279908897
mape: 0.026252159015100373
rsquared: 0.9993302795639958
<DatetimeArray>
['2003-01-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1124
Run 001 | Training Loss: 0.0032
Run 002 | Training Loss: 0.0025
Run 003 | Training Loss: 0.0017
Run 004 | Training Loss: 0.0015
mse: 7.780537585763722
rmse: 2.789361501448624
mape: 0.02709634906737389
rsquared: 0.9990665648258259
<DatetimeArray>
['2003-01-22 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1235
Run 001 | Training Loss: 0.0018
Run 002 | Training Loss: 0.0012
Run 003 | Training Loss: 0.0010
Run 004 | Training Loss: 0.0009
mse: 6.205806432053898
rmse: 2.49114560635341
mape: 0.024383267934863867
rsquared: 0.9993465027192279
<DatetimeArray>
['2003-01-23 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0703
Run 001 | Training Loss: 0.0020
Run 002 | Training Loss: 0.0014
Run 003 | Training Loss: 0.0012
Run 004 | Training Loss: 0.0011
mse: 38.10947751016051
rmse: 6.173287415159002
mape: 0.025061091866125422
rsquared: 0.9981674658499438
<DatetimeArray>
['2003-01-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0865
Run 001 | Training Loss: 0.0020
Run 002 | Training Loss: 0.0015
Run 003 | Training Loss: 0.0012
Run 004 | Training Loss: 0.0010
mse: 9.728180991295787
rmse: 3.1190032047588194
mape: 0.022932299657140578
rsquared: 0.9993540723360096
<DatetimeArray>
['2003-01-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0261
Run 001 | Training Loss: 0.0015
Run 002 | Training Loss: 0.0012
Run 003 | Training Loss: 0.0009
Run 004 | Training Loss: 0.0008
mse: 18.547294149750805
rmse: 4.306656957519464
mape: 0.02401715456472396
rsquared: 0.9984931779520171
<DatetimeArray>
['2003-01-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2638
Run 001 | Training Loss: 0.0038
Run 002 | Training Loss: 0.0018
Run 003 | Training Loss: 0.0011
Run 004 | Training Loss: 0.0009
mse: 19.482922253984928
rmse: 4.413946335648512
mape: 0.019855263598646103
rsquared: 0.9989985455141281
<DatetimeArray>
['2003-01-29 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1950
Run 001 | Training Loss: 0.0024
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 2.957630427302876
rmse: 1.7197762724560646
mape: 0.02052157284137983
rsquared: 0.9997112327487749
<DatetimeArray>
['2003-01-30 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0440
Run 001 | Training Loss: 0.0011
Run 002 | Training Loss: 0.0008
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 6.381406207715201
rmse: 2.5261445342092363
mape: 0.021596112348726968
rsquared: 0.9995735311213586
<DatetimeArray>
['2003-01-31 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0063
Run 001 | Training Loss: 0.0013
Run 002 | Training Loss: 0.0007
Run 003 | Training Loss: 0.0006
Run 004 | Training Loss: 0.0005
mse: 4.26126635984835
rmse: 2.0642834979353855
mape: 0.018439220638606927
rsquared: 0.9996840672886749
<DatetimeArray>
['2003-02-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0161
Run 001 | Training Loss: 0.0009
Run 002 | Training Loss: 0.0006
Run 003 | Training Loss: 0.0005
Run 004 | Training Loss: 0.0005
mse: 7.060680232635373
rmse: 2.657194052498871
mape: 0.018240259920001407
rsquared: 0.9993815706495589
<DatetimeArray>
['2003-02-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.4847
Run 001 | Training Loss: 0.0021
Run 002 | Training Loss: 0.0010
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 1.955696653184478
rmse: 1.3984622458917073
mape: 0.01779872204951982
rsquared: 0.9997675287386872
<DatetimeArray>
['2003-02-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1055
Run 001 | Training Loss: 0.0014
Run 002 | Training Loss: 0.0007
Run 003 | Training Loss: 0.0006
Run 004 | Training Loss: 0.0005
mse: 3.6342232176252494
rmse: 1.9063638733529467
mape: 0.02003957990506541
rsquared: 0.9995362382596503
<DatetimeArray>
['2003-02-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0806
Run 001 | Training Loss: 0.0017
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 2.4917412999475848
rmse: 1.578525039379352
mape: 0.02040899885346353
rsquared: 0.9995672179752424
<DatetimeArray>
['2003-02-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1072
Run 001 | Training Loss: 0.0013
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0008
Run 004 | Training Loss: 0.0008
mse: 4.918147285891834
rmse: 2.217689627944324
mape: 0.020851130708203443
rsquared: 0.9993790288416448
<DatetimeArray>
['2003-02-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0201
Run 001 | Training Loss: 0.0009
Run 002 | Training Loss: 0.0007
Run 003 | Training Loss: 0.0006
Run 004 | Training Loss: 0.0006
mse: 3.5303815163764924
rmse: 1.878930950401449
mape: 0.024259072458199124
rsquared: 0.9995913517661679
<DatetimeArray>
['2003-02-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0323
Run 001 | Training Loss: 0.0008
Run 002 | Training Loss: 0.0006
Run 003 | Training Loss: 0.0006
Run 004 | Training Loss: 0.0006
mse: 2.548067510771972
rmse: 1.5962667417358454
mape: 0.02007965881009762
rsquared: 0.9996565745451067
<DatetimeArray>
['2003-02-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2721
Run 001 | Training Loss: 0.0027
Run 002 | Training Loss: 0.0017
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0011
mse: 7.294520437789511
rmse: 2.7008369883777714
mape: 0.026985320291152866
rsquared: 0.9994144464530701
<DatetimeArray>
['2003-02-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.8955
Run 001 | Training Loss: 0.0031
Run 002 | Training Loss: 0.0017
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0010
mse: 5.133791934847817
rmse: 2.265787266017668
mape: 0.024833055918675823
rsquared: 0.9992595911454835
<DatetimeArray>
['2003-02-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0603
Run 001 | Training Loss: 0.0030
Run 002 | Training Loss: 0.0020
Run 003 | Training Loss: 0.0017
Run 004 | Training Loss: 0.0013
mse: 4.36110817600366
rmse: 2.0883266449489315
mape: 0.023888103372594935
rsquared: 0.9995053827857565
<DatetimeArray>
['2003-02-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1205
Run 001 | Training Loss: 0.0015
Run 002 | Training Loss: 0.0008
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0005
mse: 1.9325255994869388
rmse: 1.390153084910773
mape: 0.01677622695291106
rsquared: 0.9997568513812208
<DatetimeArray>
['2003-02-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0212
Run 001 | Training Loss: 0.0006
Run 002 | Training Loss: 0.0004
Run 003 | Training Loss: 0.0004
Run 004 | Training Loss: 0.0003
mse: 1.9979506411733983
rmse: 1.4134888189063959
mape: 0.012838198348270182
rsquared: 0.9997879595759224
<DatetimeArray>
['2003-02-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0025
Run 001 | Training Loss: 0.0004
Run 002 | Training Loss: 0.0003
Run 003 | Training Loss: 0.0003
Run 004 | Training Loss: 0.0002
mse: 0.8611944455617259
rmse: 0.9280056279795538
mape: 0.012207804374120208
rsquared: 0.9998921476836616
<DatetimeArray>
['2003-02-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2794
Run 001 | Training Loss: 0.0018
Run 002 | Training Loss: 0.0007
Run 003 | Training Loss: 0.0005
Run 004 | Training Loss: 0.0004
mse: 25.21661302859205
rmse: 5.021614583835766
mape: 0.019763592669868112
rsquared: 0.9985541456929171
<DatetimeArray>
['2003-02-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2219
Run 001 | Training Loss: 0.0028
Run 002 | Training Loss: 0.0012
Run 003 | Training Loss: 0.0008
Run 004 | Training Loss: 0.0007
mse: 2.9369369746734346
rmse: 1.7137493908601207
mape: 0.024894068921964645
rsquared: 0.9995659217175417
<DatetimeArray>
['2003-02-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0085
Run 001 | Training Loss: 0.0009
Run 002 | Training Loss: 0.0008
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 2.0704926126220182
rmse: 1.4389206415303166
mape: 0.022309133997467295
rsquared: 0.9998201734389404
<DatetimeArray>
['2003-02-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.3846
Run 001 | Training Loss: 0.0041
Run 002 | Training Loss: 0.0021
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0010
mse: 4.895379513300258
rmse: 2.2125504544078214
mape: 0.02954429169725179
rsquared: 0.9994375186721114
<DatetimeArray>
['2003-02-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.4949
Run 001 | Training Loss: 0.0032
Run 002 | Training Loss: 0.0017
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0011
mse: 2.7927406792060703
rmse: 1.6711495083343293
mape: 0.028305123225211185
rsquared: 0.9995913269549159
<DatetimeArray>
['2003-02-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0151
Run 001 | Training Loss: 0.0022
Run 002 | Training Loss: 0.0019
Run 003 | Training Loss: 0.0016
Run 004 | Training Loss: 0.0015
mse: 3.5310764732238136
rmse: 1.879115875411576
mape: 0.028584169990775676
rsquared: 0.9995804506756943
<DatetimeArray>
['2003-03-03 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0102
Run 001 | Training Loss: 0.0012
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 3.1690751608663486
rmse: 1.7801896418264962
mape: 0.02071682273307062
rsquared: 0.9995515163045139
<DatetimeArray>
['2003-03-04 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0086
Run 001 | Training Loss: 0.0016
Run 002 | Training Loss: 0.0013
Run 003 | Training Loss: 0.0012
Run 004 | Training Loss: 0.0011
mse: 1.2100898787316592
rmse: 1.1000408532103065
mape: 0.02125971425576912
rsquared: 0.9998344919637118
<DatetimeArray>
['2003-03-05 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1351
Run 001 | Training Loss: 0.0020
Run 002 | Training Loss: 0.0012
Run 003 | Training Loss: 0.0009
Run 004 | Training Loss: 0.0007
mse: 15.433719160386294
rmse: 3.9285772437851207
mape: 0.01972019181038869
rsquared: 0.9990674563853467
<DatetimeArray>
['2003-03-06 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1607
Run 001 | Training Loss: 0.0028
Run 002 | Training Loss: 0.0016
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0010
mse: 3.2295132630144083
rmse: 1.7970846566075869
mape: 0.021127393930240688
rsquared: 0.9994503991104886
<DatetimeArray>
['2003-03-07 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1300
Run 001 | Training Loss: 0.0051
Run 002 | Training Loss: 0.0022
Run 003 | Training Loss: 0.0016
Run 004 | Training Loss: 0.0013
mse: 5.788009337494795
rmse: 2.405828201990906
mape: 0.0307808206639537
rsquared: 0.9995392304415965
<DatetimeArray>
['2003-03-10 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.1161
Run 001 | Training Loss: 0.0020
Run 002 | Training Loss: 0.0013
Run 003 | Training Loss: 0.0011
Run 004 | Training Loss: 0.0009
mse: 6.294065555999592
rmse: 2.5087976315357903
mape: 0.032680122696114
rsquared: 0.9990205842943451
<DatetimeArray>
['2003-03-11 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.3832
Run 001 | Training Loss: 0.0026
Run 002 | Training Loss: 0.0015
Run 003 | Training Loss: 0.0012
Run 004 | Training Loss: 0.0010
mse: 25.70573571888311
rmse: 5.070082417365926
mape: 0.03085092862316341
rsquared: 0.9986090240999075
<DatetimeArray>
['2003-03-12 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.9915
Run 001 | Training Loss: 0.0050
Run 002 | Training Loss: 0.0018
Run 003 | Training Loss: 0.0013
Run 004 | Training Loss: 0.0011
mse: 1.534658100904898
rmse: 1.238813182406814
mape: 0.031088501304822012
rsquared: 0.9997560080514017
<DatetimeArray>
['2003-03-13 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0416
Run 001 | Training Loss: 0.0060
Run 002 | Training Loss: 0.0037
Run 003 | Training Loss: 0.0028
Run 004 | Training Loss: 0.0021
mse: 22.33746268843202
rmse: 4.726252499436739
mape: 0.03656890523251793
rsquared: 0.9973880812038068
<DatetimeArray>
['2003-03-14 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0705
Run 001 | Training Loss: 0.0023
Run 002 | Training Loss: 0.0015
Run 003 | Training Loss: 0.0011
Run 004 | Training Loss: 0.0009
mse: 8.683181984523703
rmse: 2.9467239410103727
mape: 0.022041157124793306
rsquared: 0.9985984141776869
<DatetimeArray>
['2003-03-17 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.2873
Run 001 | Training Loss: 0.0017
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 2.461704905584161
rmse: 1.5689821240486335
mape: 0.01719847708557398
rsquared: 0.999783722169444
<DatetimeArray>
['2003-03-18 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0812
Run 001 | Training Loss: 0.0020
Run 002 | Training Loss: 0.0011
Run 003 | Training Loss: 0.0008
Run 004 | Training Loss: 0.0007
mse: 1.597537347492922
rmse: 1.2639372403299627
mape: 0.018520649234281913
rsquared: 0.9998441186250546
<DatetimeArray>
['2003-03-19 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0435
Run 001 | Training Loss: 0.0012
Run 002 | Training Loss: 0.0008
Run 003 | Training Loss: 0.0007
Run 004 | Training Loss: 0.0006
mse: 2.6952501135043954
rmse: 1.6417216918541326
mape: 0.025664969732068686
rsquared: 0.9997224176434276
<DatetimeArray>
['2003-03-20 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0161
Run 001 | Training Loss: 0.0009
Run 002 | Training Loss: 0.0007
Run 003 | Training Loss: 0.0006
Run 004 | Training Loss: 0.0005
mse: 1.1606064352872807
rmse: 1.0773144551556342
mape: 0.0179357119837367
rsquared: 0.9998554184603115
<DatetimeArray>
['2003-03-21 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0161
Run 001 | Training Loss: 0.0034
Run 002 | Training Loss: 0.0023
Run 003 | Training Loss: 0.0019
Run 004 | Training Loss: 0.0017
mse: 6.729056668294508
rmse: 2.5940425340179964
mape: 0.022266411152873738
rsquared: 0.9993529899579235
<DatetimeArray>
['2003-03-24 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0645
Run 001 | Training Loss: 0.0020
Run 002 | Training Loss: 0.0014
Run 003 | Training Loss: 0.0011
Run 004 | Training Loss: 0.0009
mse: 1.2488584442881348
rmse: 1.1175233529050455
mape: 0.02109198165150219
rsquared: 0.9998334839422872
<DatetimeArray>
['2003-03-25 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0521
Run 001 | Training Loss: 0.0007
Run 002 | Training Loss: 0.0005
Run 003 | Training Loss: 0.0005
Run 004 | Training Loss: 0.0004
mse: 1.91388398663996
rmse: 1.383431959526727
mape: 0.021145476710173236
rsquared: 0.9997766558877932
<DatetimeArray>
['2003-03-26 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0185
Run 001 | Training Loss: 0.0011
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0008
Run 004 | Training Loss: 0.0007
mse: 3.009924493778389
rmse: 1.7349133966219723
mape: 0.018094885099651827
rsquared: 0.999631978811559
<DatetimeArray>
['2003-03-27 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0101
Run 001 | Training Loss: 0.0012
Run 002 | Training Loss: 0.0009
Run 003 | Training Loss: 0.0006
Run 004 | Training Loss: 0.0005
mse: 1.294035176549202
rmse: 1.1375566695990147
mape: 0.014252931118324302
rsquared: 0.9998528291146999
<DatetimeArray>
['2003-03-28 00:00:00']
Length: 1, dtype: datetime64[ms]
Run 000 | Training Loss: 0.0729
Run 001 | Training Loss: 0.0010

,date,exdate,cp_flag,strike_price,best_bid,best_offer,volume,open_interest,impl_volatility,ddelta,...,stock_price,realized_vol,moneyness,price,price_ann,out_of_sample,mse_optim,rmse_optim,mape_optim,rsquared_optim
0,2003-01-02,2003-02-22,C,90.0,1.30,1.50,1464.0,5083.0,0.233642,0.309251,...,86.08,0.030519,0.044533,1.400,1.429631,0,190.027707,13.785054,0.108655,0.983152
1,2003-01-02,2003-02-22,C,91.0,0.95,1.15,255.0,540.0,0.224751,0.256302,...,86.08,0.030519,0.055582,1.050,1.139008,1,190.027707,13.785054,0.108655,0.983152
2,2003-01-02,2003-02-22,C,92.0,0.75,0.95,0.0,355.0,0.225981,0.216934,...,86.08,0.030519,0.066511,0.850,0.901695,1,190.027707,13.785054,0.108655,0.983152
3,2003-01-02,2003-02-22,C,94.0,0.40,0.55,0.0,835.0,0.218488,0.139982,...,86.08,0.030519,0.088018,0.475,0.557500,0,190.027707,13.785054,0.108655,0.983152
4,2003-01-02,2003-03-22,C,90.0,2.15,2.45,2028.0,13151.0,0.250788,0.361403,...,86.08,0.048298,0.044533,2.300,2.194749,0,190.027707,13.785054,0.108655,0.983152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163837,2003-12-31,2004-09-18,P,975.0,20.10,22.10,0.0,744.0,0.196156,-0.191240,...,1111.92,0.093558,-0.131406,21.100,21.417723,1,1.959831,1.399940,0.022443,0.999600
163838,2003-12-31,2004-09-18,P,995.0,23.50,25.50,607.0,4679.0,0.189753,-0.220435,...,1111.92,0.093558,-0.111101,24.500,24.954203,0,1.959831,1.399940,0.022443,0.999600
163839,2003-12-31,2004-09-18,P,900.0,11.50,13.10,3150.0,4822.0,0.222397,-0.111764,...,1111.92,0.093558,-0.211449,12.300,12.256930,1,1.959831,1.399940,0.022443,0.999600
163840,2003-12-31,2004-03-20,P,1500.0,387.50,389.50,0.0,13601.0,0.270825,-0.986928,...,1111.92,0.023402,0.299377,388.500,377.236298,1,1.959831,1.399940,0.022443,0.999600
163841,2003-12-31,2004-06-19,P,1500.0,387.20,389.20,0.0,326.0,0.193454,-0.979654,...,1111.92,0.059106,0.299377,388.200,379.799805,1,1.959831,1.399940,0.022443,0.999600

In [ ]:
# Implied vol from price for whole data models
price_dfs  = [output_xgb_price, output_ann_price_lbfgs]
price_cols = ["price_xgb", "price_ann"]

iv_xgb, iv_ann_lbfgs = implied_vol_newton_gpu_batched(
    dfs=price_dfs,
    price_cols=price_cols,
    batch_size=10_000,
)

output_xgb_price["BS_impl_vol_xgb"]         = iv_xgb.numpy()
output_ann_price_lbfgs["BS_impl_vol_ann"]   = iv_ann_lbfgs.numpy()

# Price from ivol for whole data models
iv_dfs  = [output_xgb_ivol, output_ann_ivol_lbfgs]
iv_cols = ["impl_vol_xgb", "impl_vol_ann"]

p_xgb, p_ann_lbfgs = bs_price_from_iv_gpu_batched(
    dfs=iv_dfs,
    iv_cols=iv_cols,
    batch_size=10_000,
)

output_xgb_ivol["BS_price_xgb"] = p_xgb.numpy()
output_ann_ivol_lbfgs["BS_price_ann"]  = p_ann_lbfgs.numpy()

In [ ]:
# Implied vol from price for partial data models
price_dfs  = [surface_xgb_price_data, surface_ann_lbfgs_price_data, variable_ann_lbfgs_price_data]
price_cols = ["price_xgb", "price_ann", "price_ann"]

iv_xgb_s, iv_ann_lbgfs_s, iv_ann_lbgfs_v = implied_vol_newton_gpu_batched(
    dfs=price_dfs,
    price_cols=price_cols,
    batch_size=10_000,
)

surface_xgb_price_data["BS_impl_vol_xgb"] = iv_xgb_s.numpy()
surface_ann_lbfgs_price_data["BS_impl_vol_ann"]        = iv_ann_lbgfs_s.numpy()
variable_ann_lbfgs_price_data["BS_impl_vol_ann"]        = iv_ann_lbgfs_v.numpy()

# Price from ivol for partial data models
iv_dfs  = [surface_xgb_ivol_data, surface_ann_lbfgs_ivol_data, variable_ann_lbfgs_ivol_data]
iv_cols = ["impl_vol_xgb", "impl_vol_ann", "impl_vol_ann"]

p_xgb_s, p_ann_lbgfs_s, p_ann_lbgfs_v = bs_price_from_iv_gpu_batched(
    dfs=iv_dfs,
    iv_cols=iv_cols,
    batch_size=10_000,
)

surface_xgb_price_data["BS_price_xgb"] = p_xgb_s.numpy()
surface_ann_lbfgs_price_data["BS_price_ann"]  = p_ann_lbgfs_s.numpy()
variable_ann_lbfgs_price_data["BS_price_ann"]  = p_ann_lbgfs_v.numpy()

In [14]:
# Whole data models data output for trading strategies application

outputpath1 = "C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\ivol_xgb_output_2002.dta"
outputpath3 = "C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\ivol_ann_lbfgs_output_2002.dta"
outputpath4 = "C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\price_xgb_output_2002.dta"
outputpath6 = "C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\price_ann_lbfgs_output_2002.dta"


output_xgb_ivol.to_stata(outputpath1)
output_ann_ivol_lbfgs.to_stata(outputpath3)
output_xgb_price.to_stata(outputpath4)
output_ann_price_lbfgs.to_stata(outputpath6)

In [24]:
# Surface and variable data output for trading strategies application


outputpath1 = r"C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\surface_xgb_ivol_data_2003.dta"
outputpath4 = r"C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\surface_ann_lbfgs_ivol_data_2003.dta"
outputpath5 = r"C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\variable_ann_lbfgs_ivol_data_2003.dta"
outputpath6 = r"C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\surface_xgb_price_data_2003.dta"
outputpath9 = r"C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\surface_ann_lbfgs_price_data_2003.dta"
outputpath10 = r"C:\\Users\chril\Downloads\Master_Thesis_Materials\Data\Working\Option_Metrics\models_final_output\ML_models\variable_ann_lbfgs_price_data_2003.dta"

surface_xgb_ivol_data.to_stata(outputpath1)
surface_ann_lbfgs_ivol_data.to_stata(outputpath4)
variable_ann_lbfgs_ivol_data.to_stata(outputpath5)
surface_xgb_price_data.to_stata(outputpath6)
surface_ann_lbfgs_price_data.to_stata(outputpath9)
variable_ann_lbfgs_price_data.to_stata(outputpath10)